using System;
using System.Collections.Generic;
using System.Text;
using LibGalac.Aos.Dal;
using LibGalac.Aos.Dal.Contracts;
using Galac.Adm.Ccl.Venta;
using Galac.Comun.Ccl.SttDef;
using LibGalac.Aos.Base;

namespace Galac.Adm.Dal.Venta {
    [LibMefDalComponentMetadata(typeof(clsFacturaRapidaED))]
    public class clsFacturaRapidaED: LibED, ILibMefDalComponent {
        #region Variables
        #endregion //Variables
        #region Propiedades
        #endregion //Propiedades
        #region Constructores
        public clsFacturaRapidaED(): base(){
            DbSchema = "dbo";
        }
        #endregion //Constructores
        #region Metodos Generados

        #region Miembros de ILibMefDalComponent
        string ILibMefDalComponent.DbSchema {
            get { return DbSchema; }
        }

        string ILibMefDalComponent.Name {
            get { return GetType().Name; }
        }

        string ILibMefDalComponent.Table {
            get { return "Factura"; }
        }

        bool ILibMefDalComponent.InstallTable() {
            return true; // InstalarTabla();
        }
        #endregion
        #region Queries

        private string SqlCreateTable() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine(InsSql.CreateTable("FacturaRapida", DbSchema) + " ( ");
            SQL.AppendLine("ConsecutivoCompania" + InsSql.NumericTypeForDb(10, 0) + " CONSTRAINT nnFacRapConsecutiv NOT NULL, ");
            SQL.AppendLine("Numero" + InsSql.VarCharTypeForDb(11) + " CONSTRAINT nnFacRapNumero NOT NULL, ");
            SQL.AppendLine("Fecha" + InsSql.DateTypeForDb() + " CONSTRAINT nnFacRapFecha NOT NULL, ");
            SQL.AppendLine("CodigoCliente" + InsSql.VarCharTypeForDb(10) + " CONSTRAINT d_FacRapCoCl DEFAULT (''), ");
            SQL.AppendLine("CodigoVendedor" + InsSql.VarCharTypeForDb(5) + " CONSTRAINT d_FacRapCoVe DEFAULT (''), ");
            SQL.AppendLine("Observaciones" + InsSql.VarCharTypeForDb(255) + " CONSTRAINT d_FacRapOb DEFAULT (''), ");
            SQL.AppendLine("TotalMontoExento" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapToMoEx DEFAULT (0), ");
            SQL.AppendLine("TotalBaseImponible" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapToBaIm DEFAULT (0), ");
            SQL.AppendLine("TotalRenglones" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapToRe DEFAULT (0), ");
            SQL.AppendLine("TotalIVA" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapToIV DEFAULT (0), ");
            SQL.AppendLine("TotalFactura" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapToFa DEFAULT (0), ");
            SQL.AppendLine("PorcentajeDescuento" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapPoDe DEFAULT (0), ");
            SQL.AppendLine("CodigoNota1" + InsSql.VarCharTypeForDb(10) + " CONSTRAINT d_FacRapCoNo1 DEFAULT (''), ");
            SQL.AppendLine("CodigoNota2" + InsSql.VarCharTypeForDb(10) + " CONSTRAINT d_FacRapCoNo2 DEFAULT (''), ");
            SQL.AppendLine("Moneda" + InsSql.VarCharTypeForDb(10) + " CONSTRAINT d_FacRapMo DEFAULT (''), ");
            SQL.AppendLine("NivelDePrecio" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_FacRapNiDePr DEFAULT ('0'), ");
            SQL.AppendLine("ReservarMercancia" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapReservarMe NOT NULL, ");
            SQL.AppendLine("FechaDeRetiro" + InsSql.DateTypeForDb() + " CONSTRAINT d_FacRapFeDeRe DEFAULT (''), ");
            SQL.AppendLine("CodigoAlmacen" + InsSql.VarCharTypeForDb(5) + " CONSTRAINT d_FacRapCoAl DEFAULT (''), ");
            SQL.AppendLine("StatusFactura" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_FacRapStFa DEFAULT ('0'), ");
            SQL.AppendLine("TipoDeDocumento" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapTipoDeDocu NOT NULL, ");
            SQL.AppendLine("InsertadaManualmente" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapInsertadaM NOT NULL, ");
            SQL.AppendLine("FacturaHistorica" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapFacturaHis NOT NULL, ");
            SQL.AppendLine("Cancelada" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapCancelada NOT NULL, ");
            SQL.AppendLine("UsarDireccionFiscal" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapUsarDirecc NOT NULL, ");
            SQL.AppendLine("NoDirDespachoAimprimir" + InsSql.NumericTypeForDb(10, 0) + " CONSTRAINT d_FacRapNoDiDeAi DEFAULT (0), ");
            SQL.AppendLine("CambioABolivares" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapCaAB DEFAULT (0), ");
            SQL.AppendLine("MontoDelAbono" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapMoDeAb DEFAULT (0), ");
            SQL.AppendLine("FechaDeVencimiento" + InsSql.DateTypeForDb() + " CONSTRAINT d_FacRapFeDeVe DEFAULT (''), ");
            SQL.AppendLine("CondicionesDePago" + InsSql.VarCharTypeForDb(30) + " CONSTRAINT d_FacRapCoDePa DEFAULT (''), ");
            SQL.AppendLine("FormaDeLaInicial" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_FacRapFoDeLaIn DEFAULT ('0'), ");
            SQL.AppendLine("PorcentajeDeLaInicial" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapPoDeLaIn DEFAULT (0), ");
            SQL.AppendLine("NumeroDeCuotas" + InsSql.NumericTypeForDb(10, 0) + " CONSTRAINT d_FacRapNuDeCu DEFAULT (0), ");
            SQL.AppendLine("MontoDeLasCuotas" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapMoDeLaCu DEFAULT (0), ");
            SQL.AppendLine("MontoUltimaCuota" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapMoUlCu DEFAULT (0), ");
            SQL.AppendLine("Talonario" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_FacRapTa DEFAULT ('0'), ");
            SQL.AppendLine("FormaDePago" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_FacRapFoDePa DEFAULT ('0'), ");
            SQL.AppendLine("NumDiasDeVencimiento1aCuota" + InsSql.NumericTypeForDb(10, 0) + " CONSTRAINT d_FacRapNuDiDeVe1aCu DEFAULT (0), ");
            SQL.AppendLine("EditarMontoCuota" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapEditarMont NOT NULL, ");
            SQL.AppendLine("NumeroControl" + InsSql.VarCharTypeForDb(11) + " CONSTRAINT d_FacRapNuCo DEFAULT (''), ");
            SQL.AppendLine("TipoDeTransaccion" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_FacRapTiDeTr DEFAULT ('0'), ");
            SQL.AppendLine("NumeroFacturaAfectada" + InsSql.VarCharTypeForDb(11) + " CONSTRAINT d_FacRapNuFaAf DEFAULT (''), ");
            SQL.AppendLine("NumeroPlanillaExportacion" + InsSql.VarCharTypeForDb(20) + " CONSTRAINT d_FacRapNuPlEx DEFAULT (''), ");
            SQL.AppendLine("TipoDeVenta" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_FacRapTiDeVe DEFAULT ('0'), ");
            SQL.AppendLine("UsaMaquinaFiscal" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapUsaMaquina NOT NULL, ");
            SQL.AppendLine("CodigoMaquinaRegistradora" + InsSql.VarCharTypeForDb(9) + " CONSTRAINT d_FacRapCoMaRe DEFAULT (''), ");
            SQL.AppendLine("NumeroDesde" + InsSql.VarCharTypeForDb(20) + " CONSTRAINT d_FacRapNuDe DEFAULT (''), ");
            SQL.AppendLine("NumeroHasta" + InsSql.VarCharTypeForDb(20) + " CONSTRAINT d_FacRapNuHa DEFAULT (''), ");
            SQL.AppendLine("NumeroControlHasta" + InsSql.VarCharTypeForDb(11) + " CONSTRAINT d_FacRapNuCoHa DEFAULT (''), ");
            SQL.AppendLine("MontoIvaRetenido" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapMoIvRe DEFAULT (0), ");
            SQL.AppendLine("FechaAplicacionRetIva" + InsSql.DateTypeForDb() + " CONSTRAINT d_FacRapFeApReIv DEFAULT (''), ");
            SQL.AppendLine("NumeroComprobanteRetIva" + InsSql.NumericTypeForDb(10, 0) + " CONSTRAINT d_FacRapNuCoReIv DEFAULT (0), ");
            SQL.AppendLine("FechaComprobanteRetIva" + InsSql.DateTypeForDb() + " CONSTRAINT d_FacRapFeCoReIv DEFAULT (''), ");
            SQL.AppendLine("SeRetuvoIVA" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapSeRetuvoIV NOT NULL, ");
            SQL.AppendLine("FacturaConPreciosSinIva" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapFacturaCon NOT NULL, ");
            SQL.AppendLine("VueltoDelCobroDirecto" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapVuDeCoDi DEFAULT (0), ");
            SQL.AppendLine("ConsecutivoCaja" + InsSql.NumericTypeForDb(10, 0) + " CONSTRAINT d_FacRapCoCa DEFAULT (0), ");
            SQL.AppendLine("GeneraCobroDirecto" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapGeneraCobr NOT NULL, ");
            SQL.AppendLine("FechaDeFacturaAfectada" + InsSql.DateTypeForDb() + " CONSTRAINT d_FacRapFeDeFaAf DEFAULT (''), ");
            SQL.AppendLine("FechaDeEntrega" + InsSql.DateTypeForDb() + " CONSTRAINT d_FacRapFeDeEn DEFAULT (''), ");
            SQL.AppendLine("PorcentajeDescuento1" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapPoDe1 DEFAULT (0), ");
            SQL.AppendLine("PorcentajeDescuento2" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapPoDe2 DEFAULT (0), ");
            SQL.AppendLine("MontoDescuento1" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapMoDe1 DEFAULT (0), ");
            SQL.AppendLine("MontoDescuento2" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapMoDe2 DEFAULT (0), ");
            SQL.AppendLine("CodigoLote" + InsSql.VarCharTypeForDb(10) + " CONSTRAINT d_FacRapCoLo DEFAULT (''), ");
            SQL.AppendLine("Devolucion" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapDevolucion NOT NULL, ");
            SQL.AppendLine("PorcentajeAlicuota1" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapPoAl1 DEFAULT (0), ");
            SQL.AppendLine("PorcentajeAlicuota2" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapPoAl2 DEFAULT (0), ");
            SQL.AppendLine("PorcentajeAlicuota3" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapPoAl3 DEFAULT (0), ");
            SQL.AppendLine("MontoIvaAlicuota1" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapMoIvAl1 DEFAULT (0), ");
            SQL.AppendLine("MontoIvaAlicuota2" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapMoIvAl2 DEFAULT (0), ");
            SQL.AppendLine("MontoIvaAlicuota3" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapMoIvAl3 DEFAULT (0), ");
            SQL.AppendLine("MontoGravableAlicuota1" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapMoGrAl1 DEFAULT (0), ");
            SQL.AppendLine("MontoGravableAlicuota2" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapMoGrAl2 DEFAULT (0), ");
            SQL.AppendLine("MontoGravableAlicuota3" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_FacRapMoGrAl3 DEFAULT (0), ");
            SQL.AppendLine("RealizoCierreZ" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapRealizoCie NOT NULL, ");
            SQL.AppendLine("NumeroComprobanteFiscal" + InsSql.VarCharTypeForDb(12) + " CONSTRAINT d_FacRapNuCoFi DEFAULT (''), ");
            SQL.AppendLine("SerialMaquinaFiscal" + InsSql.VarCharTypeForDb(15) + " CONSTRAINT d_FacRapSeMaFi DEFAULT (''), ");
            SQL.AppendLine("AplicarPromocion" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapAplicarPro NOT NULL, ");
            SQL.AppendLine("RealizoCierreX" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapRealizoCie NOT NULL, ");
            SQL.AppendLine("HoraModificacion" + InsSql.VarCharTypeForDb(5) + " CONSTRAINT d_FacRapHoMo DEFAULT (''), ");
            SQL.AppendLine("FormaDeCobro" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_FacRapFoDeCo DEFAULT ('0'), ");
            SQL.AppendLine("OtraFormaDeCobro" + InsSql.VarCharTypeForDb(20) + " CONSTRAINT d_FacRapOtFoDeCo DEFAULT (''), ");
            SQL.AppendLine("NoCotizacionDeOrigen" + InsSql.VarCharTypeForDb(11) + " CONSTRAINT d_FacRapNoCoDeOr DEFAULT (''), ");
            SQL.AppendLine("NoContrato" + InsSql.VarCharTypeForDb(5) + " CONSTRAINT d_FacRapNoCo DEFAULT (''), ");
            SQL.AppendLine("ConsecutivoVehiculo" + InsSql.NumericTypeForDb(10, 0) + " CONSTRAINT d_FacRapCoVe DEFAULT (0), ");
            SQL.AppendLine("ConsecutivoAlmacen" + InsSql.NumericTypeForDb(10, 0) + " CONSTRAINT d_FacRapCoAl DEFAULT (0), ");
            SQL.AppendLine("GeneradaPorNotaEntrega" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapGeneradaPo NOT NULL, ");
            SQL.AppendLine("EmitidaEnFacturaNumero" + InsSql.VarCharTypeForDb(11) + " CONSTRAINT d_FacRapEmEnFaNu DEFAULT (''), ");
            SQL.AppendLine("CodigoMoneda" + InsSql.VarCharTypeForDb(4) + " CONSTRAINT d_FacRapCoMo DEFAULT (''), ");
            SQL.AppendLine("NumeroParaResumen" + InsSql.NumericTypeForDb(10, 0) + " CONSTRAINT d_FacRapNuPaRe DEFAULT (0), ");
            SQL.AppendLine("NumeroResumenDiario" + InsSql.VarCharTypeForDb(8) + " CONSTRAINT d_FacRapNuReDi DEFAULT (''), ");
            SQL.AppendLine("NoControlDespachoDeOrigen" + InsSql.VarCharTypeForDb(30) + " CONSTRAINT d_FacRapNoCoDeDeOr DEFAULT (''), ");
            SQL.AppendLine("ImprimeFiscal" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapImprimeFis NOT NULL, ");
            SQL.AppendLine("EsDiferida" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapEsDiferida NOT NULL, ");
            SQL.AppendLine("EsOriginalmenteDiferida" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapEsOriginal NOT NULL, ");
            SQL.AppendLine("SeContabilizoIvaDiferido" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapSeContabil NOT NULL, ");
            SQL.AppendLine("AplicaDecretoIvaEspecial" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapAplicaDecr NOT NULL, ");
            SQL.AppendLine("EsGeneradaPorPuntoDeVenta" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnFacRapEsGenerada NOT NULL, ");
            SQL.AppendLine("NombreOperador" + InsSql.VarCharTypeForDb(10) + ", ");
            SQL.AppendLine("FechaUltimaModificacion" + InsSql.DateTypeForDb() + ", ");
            SQL.AppendLine("fldTimeStamp" + InsSql.TimeStampTypeForDb() + ",");
            SQL.AppendLine("CONSTRAINT p_FacturaRapida PRIMARY KEY CLUSTERED");
            SQL.AppendLine("(ConsecutivoCompania ASC, Numero ASC, TipoDeDocumento ASC)");
            SQL.AppendLine(", CONSTRAINT fk_FacturaRapidaCliente FOREIGN KEY (ConsecutivoCompania, CodigoCliente)");
            SQL.AppendLine("REFERENCES Saw.Cliente(ConsecutivoCompania, codigo)");
            SQL.AppendLine("ON UPDATE CASCADE");
            SQL.AppendLine(", CONSTRAINT fk_FacturaRapidaVendedor FOREIGN KEY (ConsecutivoCompania, CodigoVendedor)");
            SQL.AppendLine("REFERENCES dbo.Vendedor(ConsecutivoCompania, codigo)");
            SQL.AppendLine("ON UPDATE CASCADE");
            SQL.AppendLine(", CONSTRAINT fk_FacturaRapidaMoneda FOREIGN KEY (Moneda)");
            SQL.AppendLine("REFERENCES Comun.Moneda(Nombre)");
            SQL.AppendLine("ON UPDATE CASCADE");
            SQL.AppendLine(", CONSTRAINT fk_FacturaRapidaAlmacen FOREIGN KEY (ConsecutivoCompania, CodigoAlmacen)");
            SQL.AppendLine("REFERENCES Saw.Almacen(ConsecutivoCompania, Codigo)");
            SQL.AppendLine("ON UPDATE CASCADE");
            SQL.AppendLine(", CONSTRAINT fk_FacturaRapidaMaquinaFiscal FOREIGN KEY (ConsecutivoCompania, CodigoMaquinaRegistradora)");
            SQL.AppendLine("REFERENCES Saw.MaquinaFiscal(ConsecutivoCompania, ConsecutivoMaquinaFiscal)");
            SQL.AppendLine("ON UPDATE CASCADE");
            SQL.AppendLine(", CONSTRAINT fk_FacturaRapidaCaja FOREIGN KEY (ConsecutivoCompania, ConsecutivoCaja)");
            SQL.AppendLine("REFERENCES Adm.Caja(ConsecutivoCompania, Consecutivo)");
            SQL.AppendLine("ON UPDATE CASCADE");
            SQL.AppendLine(", CONSTRAINT fk_FacturaRapidaMoneda FOREIGN KEY (CodigoMoneda)");
            SQL.AppendLine("REFERENCES Comun.Moneda(Codigo)");
            SQL.AppendLine("ON UPDATE CASCADE");
            SQL.AppendLine(",CONSTRAINT u_FacRapNumero UNIQUE NONCLUSTERED (ConsecutivoCompania, Numero)");
            SQL.AppendLine(")");
            return SQL.ToString();
        }

        private string SqlViewB1() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("SELECT Factura.ConsecutivoCompania, Factura.Numero, Factura.Fecha, Factura.CodigoCliente");
            SQL.AppendLine(", Cliente.NumeroRIF, Cliente.Nombre as NombreCliente, Factura.CodigoVendedor, Factura.TotalMontoExento, Factura.TotalBaseImponible");
            SQL.AppendLine(", Factura.TotalRenglones, Factura.TotalIVA, Factura.TotalFactura, Factura.PorcentajeDescuento");
            SQL.AppendLine(", Factura.Moneda, Factura.NivelDePrecio, Factura.StatusFactura, " + DbSchema + ".Gv_EnumStatusFactura.StrValue AS StatusFacturaStr, Factura.TipoDeDocumento, " + DbSchema + ".Gv_EnumTipoDocumentoFactura.StrValue AS TipoDeDocumentoStr");
            SQL.AppendLine(", Factura.InsertadaManualmente, Factura.FacturaHistorica, Factura.Cancelada");
            SQL.AppendLine(", Factura.UsarDireccionFiscal, Factura.NoDirDespachoAimprimir, Factura.CambioABolivares, Factura.MontoDelAbono");
            SQL.AppendLine(", Factura.MontoIvaRetenido, Factura.FechaAplicacionRetIVA, Factura.FacturaConPreciosSinIva, Factura.ConsecutivoCaja");
            SQL.AppendLine(", Factura.GeneraCobroDirecto, Factura.PorcentajeAlicuota1, Factura.PorcentajeAlicuota2, Factura.PorcentajeAlicuota3");
            SQL.AppendLine(", Factura.MontoIvaAlicuota2, Factura.MontoIvaAlicuota1, Factura.MontoIvaAlicuota3, Factura.MontoGravableAlicuota1");
            SQL.AppendLine(", Factura.MontoGravableAlicuota2, Factura.MontoGravableAlicuota3, Factura.ConsecutivoAlmacen, Vendedor.Nombre AS NombreVendedor");
            SQL.AppendLine(", Factura.CodigoAlmacen, Factura.ImprimeFiscal, Factura.NumeroControl, Factura.CodigoMoneda ");
            SQL.AppendLine(", Factura.SerialMaquinaFiscal, Factura.AplicaDecretoIvaEspecial ");
            SQL.AppendLine(", Factura.EsGeneradaPorPuntoDeVenta, Factura.CambioMostrarTotalEnDivisas, Factura.CodigoMonedaDeCobro, MonedaDeCobro.Nombre AS NombreMonedaDeCobro, Factura.NombreOperador");
            SQL.AppendLine(", Factura.NroDiasMantenerCambioAMonedaLocal, Factura.FechaLimiteCambioAMonedaLocal, Factura.FechaUltimaModificacion");
            SQL.AppendLine(", Factura.fldTimeStamp, CAST(Factura.fldTimeStamp AS bigint) AS fldTimeStampBigint");
            SQL.AppendLine("FROM " + DbSchema + ".Factura");
            SQL.AppendLine("INNER JOIN " + DbSchema + ".Gv_EnumStatusFactura");
            SQL.AppendLine("ON " + DbSchema + ".Factura.StatusFactura COLLATE MODERN_SPANISH_CS_AS");
            SQL.AppendLine(" = " + DbSchema + ".Gv_EnumStatusFactura.DbValue");
            SQL.AppendLine("INNER JOIN " + DbSchema + ".Gv_EnumTipoDocumentoFactura");
            SQL.AppendLine("ON " + DbSchema + ".Factura.TipoDeDocumento COLLATE MODERN_SPANISH_CS_AS");
            SQL.AppendLine(" = " + DbSchema + ".Gv_EnumTipoDocumentoFactura.DbValue");
            SQL.AppendLine("INNER JOIN Cliente ON  " + DbSchema + ".Factura.CodigoCliente = Cliente.Codigo");
            SQL.AppendLine("      AND " + DbSchema + ".Factura.ConsecutivoCompania = Cliente.ConsecutivoCompania");
            SQL.AppendLine("INNER JOIN dbo.Vendedor ON  " + DbSchema + ".Factura.CodigoVendedor = dbo.Vendedor.codigo");
            SQL.AppendLine("      AND " + DbSchema + ".Factura.ConsecutivoCompania = dbo.Vendedor.ConsecutivoCompania");
            SQL.AppendLine("INNER JOIN Adm.Caja ON  " + DbSchema + ".Factura.ConsecutivoCaja = Adm.Caja.Consecutivo");
            SQL.AppendLine("      AND " + DbSchema + ".Factura.ConsecutivoCompania = Adm.Caja.ConsecutivoCompania");            
            SQL.AppendLine("INNER JOIN dbo.Moneda AS MonedaDeCobro ON  " + DbSchema + ".Factura.CodigoMonedaDeCobro = MonedaDeCobro.codigo");
            SQL.AppendLine("      AND  MonedaDeCobro.Activa = 'S'");
            return SQL.ToString();
        }

        private string SqlSpInsParameters() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("@DateFormat" + InsSql.VarCharTypeForDb(3) + ",");
            SQL.AppendLine("@ConsecutivoCompania" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@Numero" + InsSql.VarCharTypeForDb(11) + ",");
            SQL.AppendLine("@Fecha" + InsSql.DateTypeForDb() + " = '01/01/1900',");
            SQL.AppendLine("@CodigoCliente" + InsSql.VarCharTypeForDb(10) + " = '',");
            SQL.AppendLine("@CodigoVendedor" + InsSql.VarCharTypeForDb(5) + ",");
            SQL.AppendLine("@Observaciones" + InsSql.VarCharTypeForDb(7000) + " = '',");
            SQL.AppendLine("@TotalMontoExento" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@TotalBaseImponible" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@TotalRenglones" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@TotalIVA" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@TotalFactura" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@PorcentajeDescuento" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@CodigoNota1" + InsSql.VarCharTypeForDb(10) + " = '',");
            SQL.AppendLine("@CodigoNota2" + InsSql.VarCharTypeForDb(10) + " = '',");
            SQL.AppendLine("@Moneda" + InsSql.VarCharTypeForDb(80) + " = '',");
            SQL.AppendLine("@NivelDePrecio" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@ReservarMercancia" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@FechaDeRetiro" + InsSql.DateTypeForDb() + " = '01/01/1900',");
            SQL.AppendLine("@CodigoAlmacen" + InsSql.VarCharTypeForDb(5) + ",");
            SQL.AppendLine("@StatusFactura" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@TipoDeDocumento" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@InsertadaManualmente" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@FacturaHistorica" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@Cancelada" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@UsarDireccionFiscal" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@NoDirDespachoAimprimir" + InsSql.NumericTypeForDb(10, 0) + " = 0,");
            SQL.AppendLine("@CambioABolivares" + InsSql.DecimalTypeForDb(25, 4) + " = 1,");
            SQL.AppendLine("@MontoDelAbono" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@FechaDeVencimiento" + InsSql.DateTypeForDb() + " = '01/01/1900',");
            SQL.AppendLine("@CondicionesDePago" + InsSql.VarCharTypeForDb(30) + " = '',");
            SQL.AppendLine("@FormaDeLaInicial" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@PorcentajeDeLaInicial" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@NumeroDeCuotas" + InsSql.NumericTypeForDb(10, 0) + " = 0,");
            SQL.AppendLine("@MontoDeLasCuotas" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoUltimaCuota" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@Talonario" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@FormaDePago" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@NumDiasDeVencimiento1aCuota" + InsSql.NumericTypeForDb(10, 0) + " = 0,");
            SQL.AppendLine("@EditarMontoCuota" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@NumeroControl" + InsSql.VarCharTypeForDb(11) + " = '',");
            SQL.AppendLine("@TipoDeTransaccion" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@NumeroFacturaAfectada" + InsSql.VarCharTypeForDb(11) + " = '',");
            SQL.AppendLine("@NumeroPlanillaExportacion" + InsSql.VarCharTypeForDb(20) + " = '',");
            SQL.AppendLine("@TipoDeVenta" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@UsaMaquinaFiscal" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@CodigoMaquinaRegistradora" + InsSql.VarCharTypeForDb(9) + ",");
            SQL.AppendLine("@NumeroDesde" + InsSql.VarCharTypeForDb(20) + " = '',");
            SQL.AppendLine("@NumeroHasta" + InsSql.VarCharTypeForDb(20) + " = '',");
            SQL.AppendLine("@NumeroControlHasta" + InsSql.VarCharTypeForDb(11) + " = '',");
            SQL.AppendLine("@MontoIvaRetenido" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@FechaAplicacionRetIva" + InsSql.DateTypeForDb() + " = '01/01/1900',");
            SQL.AppendLine("@NumeroComprobanteRetIva" + InsSql.NumericTypeForDb(10, 0) + " = 0,");
            SQL.AppendLine("@FechaComprobanteRetIva" + InsSql.DateTypeForDb() + " = '01/01/1900',");
            SQL.AppendLine("@SeRetuvoIVA" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@FacturaConPreciosSinIva" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@VueltoDelCobroDirecto" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@ConsecutivoCaja" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@GeneraCobroDirecto" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@FechaDeFacturaAfectada" + InsSql.DateTypeForDb() + " = '01/01/1900',");
            SQL.AppendLine("@FechaDeEntrega" + InsSql.DateTypeForDb() + " = '01/01/1900',");
            SQL.AppendLine("@PorcentajeDescuento1" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@PorcentajeDescuento2" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoDescuento1" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoDescuento2" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@CodigoLote" + InsSql.VarCharTypeForDb(10) + " = '',");
            SQL.AppendLine("@Devolucion" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@PorcentajeAlicuota1" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@PorcentajeAlicuota2" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@PorcentajeAlicuota3" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoIvaAlicuota1" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoIvaAlicuota2" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoIvaAlicuota3" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoGravableAlicuota1" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoGravableAlicuota2" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoGravableAlicuota3" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@RealizoCierreZ" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@NumeroComprobanteFiscal" + InsSql.VarCharTypeForDb(12) + " = '',");
            SQL.AppendLine("@SerialMaquinaFiscal" + InsSql.VarCharTypeForDb(15) + " = '',");
            SQL.AppendLine("@AplicarPromocion" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@RealizoCierreX" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@HoraModificacion" + InsSql.VarCharTypeForDb(5) + " = '',");
            SQL.AppendLine("@FormaDeCobro" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@OtraFormaDeCobro" + InsSql.VarCharTypeForDb(20) + " = '',");
            SQL.AppendLine("@NoCotizacionDeOrigen" + InsSql.VarCharTypeForDb(11) + " = '',");
            SQL.AppendLine("@NoContrato" + InsSql.VarCharTypeForDb(5) + " = '',");
            SQL.AppendLine("@ConsecutivoVehiculo" + InsSql.NumericTypeForDb(10, 0) + " = 0,");
            SQL.AppendLine("@ConsecutivoAlmacen" + InsSql.NumericTypeForDb(10, 0) + " = 0,");
            SQL.AppendLine("@GeneradaPorNotaEntrega" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@EmitidaEnFacturaNumero" + InsSql.VarCharTypeForDb(11) + " = '',");
            SQL.AppendLine("@CodigoMoneda" + InsSql.VarCharTypeForDb(4) + ",");
            SQL.AppendLine("@NumeroParaResumen" + InsSql.NumericTypeForDb(10, 0) + " = 0,");
            SQL.AppendLine("@NumeroResumenDiario" + InsSql.VarCharTypeForDb(8) + " = '',");
            SQL.AppendLine("@NoControlDespachoDeOrigen" + InsSql.VarCharTypeForDb(30) + " = '',");
            SQL.AppendLine("@ImprimeFiscal" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@EsDiferida" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@EsOriginalmenteDiferida" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@SeContabilizoIvaDiferido" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@AplicaDecretoIvaEspecial" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@EsGeneradaPorPuntoDeVenta" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@CambioMostrarTotalEnDivisas" + InsSql.DecimalTypeForDb(25,4) + " = 1,");
            SQL.AppendLine("@CodigoMonedaDeCobro" + InsSql.VarCharTypeForDb(4) + ",");
            SQL.AppendLine("@NombreOperador" + InsSql.VarCharTypeForDb(10) + " = '',");
            SQL.AppendLine("@NroDiasMantenerCambioAMonedaLocal" + InsSql.NumericTypeForDb(10,0) + " = 0,");
            SQL.AppendLine("@FechaLimiteCambioAMonedaLocal" + InsSql.DateTypeForDb() + " = '01/01/1980',");
            SQL.AppendLine("@FechaUltimaModificacion" + InsSql.DateTypeForDb() + " = '01/01/1900'");
            return SQL.ToString();
        }

        private string SqlSpIns() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("BEGIN");
            SQL.AppendLine("   SET NOCOUNT ON;");
            SQL.AppendLine("   SET DATEFORMAT @DateFormat");
            SQL.AppendLine("   DECLARE @ReturnValue " + InsSql.NumericTypeForDb(10, 0) + "");
            SQL.AppendLine("	IF EXISTS(SELECT ConsecutivoCompania FROM Compania WHERE ConsecutivoCompania = @ConsecutivoCompania)");
            SQL.AppendLine("	BEGIN");
            SQL.AppendLine("        BEGIN TRAN");
            SQL.AppendLine("            INSERT INTO " + DbSchema + ".Factura(");
            SQL.AppendLine("            ConsecutivoCompania,");
            SQL.AppendLine("            Numero,");
            SQL.AppendLine("            Fecha,");
            SQL.AppendLine("            CodigoCliente,");
            SQL.AppendLine("            CodigoVendedor,");
            SQL.AppendLine("            Observaciones,");
            SQL.AppendLine("            TotalMontoExento,");
            SQL.AppendLine("            TotalBaseImponible,");
            SQL.AppendLine("            TotalRenglones,");
            SQL.AppendLine("            TotalIVA,");
            SQL.AppendLine("            TotalFactura,");
            SQL.AppendLine("            PorcentajeDescuento,");
            SQL.AppendLine("            CodigoNota1,");
            SQL.AppendLine("            CodigoNota2,");
            SQL.AppendLine("            Moneda,");
            SQL.AppendLine("            NivelDePrecio,");
            SQL.AppendLine("            ReservarMercancia,");
            SQL.AppendLine("            FechaDeRetiro,");
            SQL.AppendLine("            CodigoAlmacen,");
            SQL.AppendLine("            StatusFactura,");
            SQL.AppendLine("            TipoDeDocumento,");
            SQL.AppendLine("            InsertadaManualmente,");
            SQL.AppendLine("            FacturaHistorica,");
            SQL.AppendLine("            Cancelada,");
            SQL.AppendLine("            UsarDireccionFiscal,");
            SQL.AppendLine("            NoDirDespachoAimprimir,");
            SQL.AppendLine("            CambioABolivares,");
            SQL.AppendLine("            MontoDelAbono,");
            SQL.AppendLine("            FechaDeVencimiento,");
            SQL.AppendLine("            CondicionesDePago,");
            SQL.AppendLine("            FormaDeLaInicial,");
            SQL.AppendLine("            PorcentajeDeLaInicial,");
            SQL.AppendLine("            NumeroDeCuotas,");
            SQL.AppendLine("            MontoDeLasCuotas,");
            SQL.AppendLine("            MontoUltimaCuota,");
            SQL.AppendLine("            Talonario,");
            SQL.AppendLine("            FormaDePago,");
            SQL.AppendLine("            NumDiasDeVencimiento1aCuota,");
            SQL.AppendLine("            EditarMontoCuota,");
            SQL.AppendLine("            NumeroControl,");
            SQL.AppendLine("            TipoDeTransaccion,");
            SQL.AppendLine("            NumeroFacturaAfectada,");
            SQL.AppendLine("            NumeroPlanillaExportacion,");
            SQL.AppendLine("            TipoDeVenta,");
            SQL.AppendLine("            UsaMaquinaFiscal,");
            SQL.AppendLine("            CodigoMaquinaRegistradora,");
            SQL.AppendLine("            NumeroDesde,");
            SQL.AppendLine("            NumeroHasta,");
            SQL.AppendLine("            NumeroControlHasta,");
            SQL.AppendLine("            MontoIvaRetenido,");
            SQL.AppendLine("            FechaAplicacionRetIva,");
            SQL.AppendLine("            NumeroComprobanteRetIva,");
            SQL.AppendLine("            FechaComprobanteRetIva,");
            SQL.AppendLine("            SeRetuvoIVA,");
            SQL.AppendLine("            FacturaConPreciosSinIva,");
            SQL.AppendLine("            VueltoDelCobroDirecto,");
            SQL.AppendLine("            ConsecutivoCaja,");
            SQL.AppendLine("            GeneraCobroDirecto,");
            SQL.AppendLine("            FechaDeFacturaAfectada,");
            SQL.AppendLine("            FechaDeEntrega,");
            SQL.AppendLine("            PorcentajeDescuento1,");
            SQL.AppendLine("            PorcentajeDescuento2,");
            SQL.AppendLine("            MontoDescuento1,");
            SQL.AppendLine("            MontoDescuento2,");
            SQL.AppendLine("            CodigoLote,");
            SQL.AppendLine("            Devolucion,");
            SQL.AppendLine("            PorcentajeAlicuota1,");
            SQL.AppendLine("            PorcentajeAlicuota2,");
            SQL.AppendLine("            PorcentajeAlicuota3,");
            SQL.AppendLine("            MontoIvaAlicuota1,");
            SQL.AppendLine("            MontoIvaAlicuota2,");
            SQL.AppendLine("            MontoIvaAlicuota3,");
            SQL.AppendLine("            MontoGravableAlicuota1,");
            SQL.AppendLine("            MontoGravableAlicuota2,");
            SQL.AppendLine("            MontoGravableAlicuota3,");
            SQL.AppendLine("            RealizoCierreZ,");
            SQL.AppendLine("            NumeroComprobanteFiscal,");
            SQL.AppendLine("            SerialMaquinaFiscal,");
            SQL.AppendLine("            AplicarPromocion,");
            SQL.AppendLine("            RealizoCierreX,");
            SQL.AppendLine("            HoraModificacion,");
            SQL.AppendLine("            FormaDeCobro,");
            SQL.AppendLine("            OtraFormaDeCobro,");
            SQL.AppendLine("            NoCotizacionDeOrigen,");
            SQL.AppendLine("            NoContrato,");
            SQL.AppendLine("            ConsecutivoVehiculo,");
            SQL.AppendLine("            ConsecutivoAlmacen,");
            SQL.AppendLine("            GeneradaPorNotaEntrega,");
            SQL.AppendLine("            EmitidaEnFacturaNumero,");
            SQL.AppendLine("            CodigoMoneda,");
            SQL.AppendLine("            NumeroParaResumen,");
            SQL.AppendLine("            NumeroResumenDiario,");
            SQL.AppendLine("            NoControlDespachoDeOrigen,");
            SQL.AppendLine("            ImprimeFiscal,");
            SQL.AppendLine("            EsDiferida,");
            SQL.AppendLine("            EsOriginalmenteDiferida,");
            SQL.AppendLine("            SeContabilizoIvaDiferido,");
            SQL.AppendLine("            AplicaDecretoIvaEspecial,");
            SQL.AppendLine("            EsGeneradaPorPuntoDeVenta,");
            SQL.AppendLine("            CambioMostrarTotalEnDivisas,");
            SQL.AppendLine("            CodigoMonedaDeCobro,");
            SQL.AppendLine("            NombreOperador,");
            SQL.AppendLine("            NroDiasMantenerCambioAMonedaLocal,");
            SQL.AppendLine("            FechaLimiteCambioAMonedaLocal,");
            SQL.AppendLine("            FechaUltimaModificacion)");
            SQL.AppendLine("            VALUES(");
            SQL.AppendLine("            @ConsecutivoCompania,");
            SQL.AppendLine("            @Numero,");
            SQL.AppendLine("            @Fecha,");
            SQL.AppendLine("            @CodigoCliente,");
            SQL.AppendLine("            @CodigoVendedor,");
            SQL.AppendLine("            @Observaciones,");
            SQL.AppendLine("            @TotalMontoExento,");
            SQL.AppendLine("            @TotalBaseImponible,");
            SQL.AppendLine("            @TotalRenglones,");
            SQL.AppendLine("            @TotalIVA,");
            SQL.AppendLine("            @TotalFactura,");
            SQL.AppendLine("            @PorcentajeDescuento,");
            SQL.AppendLine("            @CodigoNota1,");
            SQL.AppendLine("            @CodigoNota2,");
            SQL.AppendLine("            @Moneda,");
            SQL.AppendLine("            @NivelDePrecio,");
            SQL.AppendLine("            @ReservarMercancia,");
            SQL.AppendLine("            @FechaDeRetiro,");
            SQL.AppendLine("            @CodigoAlmacen,");
            SQL.AppendLine("            @StatusFactura,");
            SQL.AppendLine("            @TipoDeDocumento,");
            SQL.AppendLine("            @InsertadaManualmente,");
            SQL.AppendLine("            @FacturaHistorica,");
            SQL.AppendLine("            @Cancelada,");
            SQL.AppendLine("            @UsarDireccionFiscal,");
            SQL.AppendLine("            @NoDirDespachoAimprimir,");
            SQL.AppendLine("            @CambioABolivares,");
            SQL.AppendLine("            @MontoDelAbono,");
            SQL.AppendLine("            @FechaDeVencimiento,");
            SQL.AppendLine("            @CondicionesDePago,");
            SQL.AppendLine("            @FormaDeLaInicial,");
            SQL.AppendLine("            @PorcentajeDeLaInicial,");
            SQL.AppendLine("            @NumeroDeCuotas,");
            SQL.AppendLine("            @MontoDeLasCuotas,");
            SQL.AppendLine("            @MontoUltimaCuota,");
            SQL.AppendLine("            @Talonario,");
            SQL.AppendLine("            @FormaDePago,");
            SQL.AppendLine("            @NumDiasDeVencimiento1aCuota,");
            SQL.AppendLine("            @EditarMontoCuota,");
            SQL.AppendLine("            @NumeroControl,");
            SQL.AppendLine("            @TipoDeTransaccion,");
            SQL.AppendLine("            @NumeroFacturaAfectada,");
            SQL.AppendLine("            @NumeroPlanillaExportacion,");
            SQL.AppendLine("            @TipoDeVenta,");
            SQL.AppendLine("            @UsaMaquinaFiscal,");
            SQL.AppendLine("            @CodigoMaquinaRegistradora,");
            SQL.AppendLine("            @NumeroDesde,");
            SQL.AppendLine("            @NumeroHasta,");
            SQL.AppendLine("            @NumeroControlHasta,");
            SQL.AppendLine("            @MontoIvaRetenido,");
            SQL.AppendLine("            @FechaAplicacionRetIva,");
            SQL.AppendLine("            @NumeroComprobanteRetIva,");
            SQL.AppendLine("            @FechaComprobanteRetIva,");
            SQL.AppendLine("            @SeRetuvoIVA,");
            SQL.AppendLine("            @FacturaConPreciosSinIva,");
            SQL.AppendLine("            @VueltoDelCobroDirecto,");
            SQL.AppendLine("            @ConsecutivoCaja,");
            SQL.AppendLine("            @GeneraCobroDirecto,");
            SQL.AppendLine("            @FechaDeFacturaAfectada,");
            SQL.AppendLine("            @FechaDeEntrega,");
            SQL.AppendLine("            @PorcentajeDescuento1,");
            SQL.AppendLine("            @PorcentajeDescuento2,");
            SQL.AppendLine("            @MontoDescuento1,");
            SQL.AppendLine("            @MontoDescuento2,");
            SQL.AppendLine("            @CodigoLote,");
            SQL.AppendLine("            @Devolucion,");
            SQL.AppendLine("            @PorcentajeAlicuota1,");
            SQL.AppendLine("            @PorcentajeAlicuota2,");
            SQL.AppendLine("            @PorcentajeAlicuota3,");
            SQL.AppendLine("            @MontoIvaAlicuota1,");
            SQL.AppendLine("            @MontoIvaAlicuota2,");
            SQL.AppendLine("            @MontoIvaAlicuota3,");
            SQL.AppendLine("            @MontoGravableAlicuota1,");
            SQL.AppendLine("            @MontoGravableAlicuota2,");
            SQL.AppendLine("            @MontoGravableAlicuota3,");
            SQL.AppendLine("            @RealizoCierreZ,");
            SQL.AppendLine("            @NumeroComprobanteFiscal,");
            SQL.AppendLine("            @SerialMaquinaFiscal,");
            SQL.AppendLine("            @AplicarPromocion,");
            SQL.AppendLine("            @RealizoCierreX,");
            SQL.AppendLine("            @HoraModificacion,");
            SQL.AppendLine("            @FormaDeCobro,");
            SQL.AppendLine("            @OtraFormaDeCobro,");
            SQL.AppendLine("            @NoCotizacionDeOrigen,");
            SQL.AppendLine("            @NoContrato,");
            SQL.AppendLine("            @ConsecutivoVehiculo,");
            SQL.AppendLine("            @ConsecutivoAlmacen,");
            SQL.AppendLine("            @GeneradaPorNotaEntrega,");
            SQL.AppendLine("            @EmitidaEnFacturaNumero,");
            SQL.AppendLine("            @CodigoMoneda,");
            SQL.AppendLine("            @NumeroParaResumen,");
            SQL.AppendLine("            @NumeroResumenDiario,");
            SQL.AppendLine("            @NoControlDespachoDeOrigen,");
            SQL.AppendLine("            @ImprimeFiscal,");
            SQL.AppendLine("            @EsDiferida,");
            SQL.AppendLine("            @EsOriginalmenteDiferida,");
            SQL.AppendLine("            @SeContabilizoIvaDiferido,");
            SQL.AppendLine("            @AplicaDecretoIvaEspecial,");
            SQL.AppendLine("            @EsGeneradaPorPuntoDeVenta,");
            SQL.AppendLine("            @CambioMostrarTotalEnDivisas,");
            SQL.AppendLine("            @CodigoMonedaDeCobro,");
            SQL.AppendLine("            @NombreOperador,");
            SQL.AppendLine("            @NroDiasMantenerCambioAMonedaLocal,");
            SQL.AppendLine("            @FechaLimiteCambioAMonedaLocal,");
            SQL.AppendLine("            @FechaUltimaModificacion)");
            SQL.AppendLine("            SET @ReturnValue = @@ROWCOUNT");
            SQL.AppendLine("        COMMIT TRAN");
            SQL.AppendLine("        RETURN @ReturnValue ");
            SQL.AppendLine("	END");
            SQL.AppendLine("	ELSE");
            SQL.AppendLine("		RETURN -1");
            SQL.AppendLine("END");
            return SQL.ToString();
        }

        private string SqlSpUpdParameters() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("@DateFormat" + InsSql.VarCharTypeForDb(3) + ",");
            SQL.AppendLine("@ConsecutivoCompania" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@Numero" + InsSql.VarCharTypeForDb(11) + ",");
            SQL.AppendLine("@Fecha" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@CodigoCliente" + InsSql.VarCharTypeForDb(10) + ",");
            SQL.AppendLine("@CodigoVendedor" + InsSql.VarCharTypeForDb(5) + ",");
            SQL.AppendLine("@Observaciones" + InsSql.VarCharTypeForDb(255) + ",");
            SQL.AppendLine("@TotalMontoExento" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@TotalBaseImponible" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@TotalRenglones" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@TotalIVA" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@TotalFactura" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@PorcentajeDescuento" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@CodigoNota1" + InsSql.VarCharTypeForDb(10) + ",");
            SQL.AppendLine("@CodigoNota2" + InsSql.VarCharTypeForDb(10) + ",");
            SQL.AppendLine("@Moneda" + InsSql.VarCharTypeForDb(10) + ",");
            SQL.AppendLine("@NivelDePrecio" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@ReservarMercancia" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@FechaDeRetiro" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@CodigoAlmacen" + InsSql.VarCharTypeForDb(5) + ",");
            SQL.AppendLine("@StatusFactura" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@TipoDeDocumento" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@InsertadaManualmente" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@FacturaHistorica" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@Cancelada" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@UsarDireccionFiscal" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@NoDirDespachoAimprimir" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@CambioABolivares" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoDelAbono" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@FechaDeVencimiento" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@CondicionesDePago" + InsSql.VarCharTypeForDb(30) + ",");
            SQL.AppendLine("@FormaDeLaInicial" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@PorcentajeDeLaInicial" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@NumeroDeCuotas" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@MontoDeLasCuotas" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoUltimaCuota" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@Talonario" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@FormaDePago" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@NumDiasDeVencimiento1aCuota" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@EditarMontoCuota" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@NumeroControl" + InsSql.VarCharTypeForDb(11) + ",");
            SQL.AppendLine("@TipoDeTransaccion" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@NumeroFacturaAfectada" + InsSql.VarCharTypeForDb(11) + ",");
            SQL.AppendLine("@NumeroPlanillaExportacion" + InsSql.VarCharTypeForDb(20) + ",");
            SQL.AppendLine("@TipoDeVenta" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@UsaMaquinaFiscal" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@CodigoMaquinaRegistradora" + InsSql.VarCharTypeForDb(9) + ",");
            SQL.AppendLine("@NumeroDesde" + InsSql.VarCharTypeForDb(20) + ",");
            SQL.AppendLine("@NumeroHasta" + InsSql.VarCharTypeForDb(20) + ",");
            SQL.AppendLine("@NumeroControlHasta" + InsSql.VarCharTypeForDb(11) + ",");
            SQL.AppendLine("@MontoIvaRetenido" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@FechaAplicacionRetIva" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@NumeroComprobanteRetIva" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@FechaComprobanteRetIva" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@SeRetuvoIVA" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@FacturaConPreciosSinIva" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@VueltoDelCobroDirecto" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@ConsecutivoCaja" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@GeneraCobroDirecto" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@FechaDeFacturaAfectada" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@FechaDeEntrega" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@PorcentajeDescuento1" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@PorcentajeDescuento2" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoDescuento1" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoDescuento2" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@CodigoLote" + InsSql.VarCharTypeForDb(10) + ",");
            SQL.AppendLine("@Devolucion" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@PorcentajeAlicuota1" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@PorcentajeAlicuota2" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@PorcentajeAlicuota3" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoIvaAlicuota1" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoIvaAlicuota2" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoIvaAlicuota3" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoGravableAlicuota1" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoGravableAlicuota2" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoGravableAlicuota3" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@RealizoCierreZ" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@NumeroComprobanteFiscal" + InsSql.VarCharTypeForDb(12) + ",");
            SQL.AppendLine("@SerialMaquinaFiscal" + InsSql.VarCharTypeForDb(15) + ",");
            SQL.AppendLine("@AplicarPromocion" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@RealizoCierreX" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@HoraModificacion" + InsSql.VarCharTypeForDb(5) + ",");
            SQL.AppendLine("@FormaDeCobro" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@OtraFormaDeCobro" + InsSql.VarCharTypeForDb(20) + ",");
            SQL.AppendLine("@NoCotizacionDeOrigen" + InsSql.VarCharTypeForDb(11) + ",");
            SQL.AppendLine("@NoContrato" + InsSql.VarCharTypeForDb(5) + ",");
            SQL.AppendLine("@ConsecutivoVehiculo" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@ConsecutivoAlmacen" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@GeneradaPorNotaEntrega" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@EmitidaEnFacturaNumero" + InsSql.VarCharTypeForDb(11) + ",");
            SQL.AppendLine("@CodigoMoneda" + InsSql.VarCharTypeForDb(4) + ",");
            SQL.AppendLine("@NumeroParaResumen" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@NumeroResumenDiario" + InsSql.VarCharTypeForDb(8) + ",");
            SQL.AppendLine("@NoControlDespachoDeOrigen" + InsSql.VarCharTypeForDb(30) + ",");
            SQL.AppendLine("@ImprimeFiscal" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@EsDiferida" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@EsOriginalmenteDiferida" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@SeContabilizoIvaDiferido" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@AplicaDecretoIvaEspecial" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@EsGeneradaPorPuntoDeVenta" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@CambioMostrarTotalEnDivisas" + InsSql.DecimalTypeForDb(25,4) + ",");
            SQL.AppendLine("@CodigoMonedaDeCobro" + InsSql.VarCharTypeForDb(4) + ",");
            SQL.AppendLine("@NombreOperador" + InsSql.VarCharTypeForDb(10) + ",");
            SQL.AppendLine("@NroDiasMantenerCambioAMonedaLocal" + InsSql.NumericTypeForDb(10,0) + ",");
            SQL.AppendLine("@FechaLimiteCambioAMonedaLocal" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@FechaUltimaModificacion" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@TimeStampAsInt" + InsSql.BigintTypeForDb());
            return SQL.ToString();
        }

        private string SqlSpUpd() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("BEGIN");
            SQL.AppendLine("   SET NOCOUNT ON;");
            SQL.AppendLine("   SET DATEFORMAT @DateFormat");
            SQL.AppendLine("   DECLARE @CurrentTimeStamp timestamp");
            SQL.AppendLine("   DECLARE @ValidationMsg " + InsSql.VarCharTypeForDb(1500) + " --No puede ser más");
            SQL.AppendLine("   DECLARE @ReturnValue " + InsSql.NumericTypeForDb(10, 0) + "");
            //SQL.AppendLine("--DECLARE @CanBeChanged bit");
            SQL.AppendLine("   SET @ReturnValue = -1");
            SQL.AppendLine("   SET @ValidationMsg = ''");
            SQL.AppendLine("   IF EXISTS(SELECT ConsecutivoCompania FROM " + DbSchema + ".Factura WHERE ConsecutivoCompania = @ConsecutivoCompania AND Numero = @Numero AND TipoDeDocumento = @TipoDeDocumento)");
            SQL.AppendLine("   BEGIN");
            SQL.AppendLine("      SELECT @CurrentTimeStamp = fldTimeStamp FROM " + DbSchema + ".Factura WHERE ConsecutivoCompania = @ConsecutivoCompania AND Numero = @Numero AND TipoDeDocumento = @TipoDeDocumento");
            SQL.AppendLine("      IF (CAST(@CurrentTimeStamp AS bigint) = @TimeStampAsInt)");
            SQL.AppendLine("      BEGIN");
            SQL.AppendLine("--Para Validaciones de FK Lógicas crear e invocar:DECLARE @CanBeChanged bit; EXEC @CanBeChanged = " + DbSchema + ".Gp_FacturacionRapidaCanBeUpdated @ConsecutivoCompania,@Numero,@TipoDeDocumento, @CurrentTimeStamp, @ValidationMsg out");
            //SQL.AppendLine("--IF @CanBeChanged = 1 --True");
            //SQL.AppendLine("--BEGIN");
            SQL.AppendLine("         BEGIN TRAN");
            SQL.AppendLine("         UPDATE " + DbSchema + ".Factura");
            SQL.AppendLine("            SET Fecha = @Fecha,");
            SQL.AppendLine("               CodigoCliente = @CodigoCliente,");
            SQL.AppendLine("               CodigoVendedor = @CodigoVendedor,");
            SQL.AppendLine("               Observaciones = @Observaciones,");
            SQL.AppendLine("               TotalMontoExento = @TotalMontoExento,");
            SQL.AppendLine("               TotalBaseImponible = @TotalBaseImponible,");
            SQL.AppendLine("               TotalRenglones = @TotalRenglones,");
            SQL.AppendLine("               TotalIVA = @TotalIVA,");
            SQL.AppendLine("               TotalFactura = @TotalFactura,");
            SQL.AppendLine("               PorcentajeDescuento = @PorcentajeDescuento,");
            SQL.AppendLine("               CodigoNota1 = @CodigoNota1,");
            SQL.AppendLine("               CodigoNota2 = @CodigoNota2,");
            SQL.AppendLine("               Moneda = @Moneda,");
            SQL.AppendLine("               NivelDePrecio = @NivelDePrecio,");
            SQL.AppendLine("               ReservarMercancia = @ReservarMercancia,");
            SQL.AppendLine("               FechaDeRetiro = @FechaDeRetiro,");
            SQL.AppendLine("               CodigoAlmacen = @CodigoAlmacen,");
            SQL.AppendLine("               StatusFactura = @StatusFactura,");
            SQL.AppendLine("               InsertadaManualmente = @InsertadaManualmente,");
            SQL.AppendLine("               FacturaHistorica = @FacturaHistorica,");
            SQL.AppendLine("               Cancelada = @Cancelada,");
            SQL.AppendLine("               UsarDireccionFiscal = @UsarDireccionFiscal,");
            SQL.AppendLine("               NoDirDespachoAimprimir = @NoDirDespachoAimprimir,");
            SQL.AppendLine("               CambioABolivares = @CambioABolivares,");
            SQL.AppendLine("               MontoDelAbono = @MontoDelAbono,");
            SQL.AppendLine("               FechaDeVencimiento = @FechaDeVencimiento,");
            SQL.AppendLine("               CondicionesDePago = @CondicionesDePago,");
            SQL.AppendLine("               FormaDeLaInicial = @FormaDeLaInicial,");
            SQL.AppendLine("               PorcentajeDeLaInicial = @PorcentajeDeLaInicial,");
            SQL.AppendLine("               NumeroDeCuotas = @NumeroDeCuotas,");
            SQL.AppendLine("               MontoDeLasCuotas = @MontoDeLasCuotas,");
            SQL.AppendLine("               MontoUltimaCuota = @MontoUltimaCuota,");
            SQL.AppendLine("               Talonario = @Talonario,");
            SQL.AppendLine("               FormaDePago = @FormaDePago,");
            SQL.AppendLine("               NumDiasDeVencimiento1aCuota = @NumDiasDeVencimiento1aCuota,");
            SQL.AppendLine("               EditarMontoCuota = @EditarMontoCuota,");
            SQL.AppendLine("               NumeroControl = @NumeroControl,");
            SQL.AppendLine("               TipoDeTransaccion = @TipoDeTransaccion,");
            SQL.AppendLine("               NumeroFacturaAfectada = @NumeroFacturaAfectada,");
            SQL.AppendLine("               NumeroPlanillaExportacion = @NumeroPlanillaExportacion,");
            SQL.AppendLine("               TipoDeVenta = @TipoDeVenta,");
            SQL.AppendLine("               UsaMaquinaFiscal = @UsaMaquinaFiscal,");
            SQL.AppendLine("               CodigoMaquinaRegistradora = @CodigoMaquinaRegistradora,");
            SQL.AppendLine("               NumeroDesde = @NumeroDesde,");
            SQL.AppendLine("               NumeroHasta = @NumeroHasta,");
            SQL.AppendLine("               NumeroControlHasta = @NumeroControlHasta,");
            SQL.AppendLine("               MontoIvaRetenido = @MontoIvaRetenido,");
            SQL.AppendLine("               FechaAplicacionRetIva = @FechaAplicacionRetIva,");
            SQL.AppendLine("               NumeroComprobanteRetIva = @NumeroComprobanteRetIva,");
            SQL.AppendLine("               FechaComprobanteRetIva = @FechaComprobanteRetIva,");
            SQL.AppendLine("               SeRetuvoIVA = @SeRetuvoIVA,");
            SQL.AppendLine("               FacturaConPreciosSinIva = @FacturaConPreciosSinIva,");
            SQL.AppendLine("               VueltoDelCobroDirecto = @VueltoDelCobroDirecto,");
            SQL.AppendLine("               ConsecutivoCaja = @ConsecutivoCaja,");
            SQL.AppendLine("               GeneraCobroDirecto = @GeneraCobroDirecto,");
            SQL.AppendLine("               FechaDeFacturaAfectada = @FechaDeFacturaAfectada,");
            SQL.AppendLine("               FechaDeEntrega = @FechaDeEntrega,");
            SQL.AppendLine("               PorcentajeDescuento1 = @PorcentajeDescuento1,");
            SQL.AppendLine("               PorcentajeDescuento2 = @PorcentajeDescuento2,");
            SQL.AppendLine("               MontoDescuento1 = @MontoDescuento1,");
            SQL.AppendLine("               MontoDescuento2 = @MontoDescuento2,");
            SQL.AppendLine("               CodigoLote = @CodigoLote,");
            SQL.AppendLine("               Devolucion = @Devolucion,");
            SQL.AppendLine("               PorcentajeAlicuota1 = @PorcentajeAlicuota1,");
            SQL.AppendLine("               PorcentajeAlicuota2 = @PorcentajeAlicuota2,");
            SQL.AppendLine("               PorcentajeAlicuota3 = @PorcentajeAlicuota3,");
            SQL.AppendLine("               MontoIvaAlicuota1 = @MontoIvaAlicuota1,");
            SQL.AppendLine("               MontoIvaAlicuota2 = @MontoIvaAlicuota2,");
            SQL.AppendLine("               MontoIvaAlicuota3 = @MontoIvaAlicuota3,");
            SQL.AppendLine("               MontoGravableAlicuota1 = @MontoGravableAlicuota1,");
            SQL.AppendLine("               MontoGravableAlicuota2 = @MontoGravableAlicuota2,");
            SQL.AppendLine("               MontoGravableAlicuota3 = @MontoGravableAlicuota3,");
            SQL.AppendLine("               RealizoCierreZ = @RealizoCierreZ,");
            SQL.AppendLine("               NumeroComprobanteFiscal = @NumeroComprobanteFiscal,");
            SQL.AppendLine("               SerialMaquinaFiscal = @SerialMaquinaFiscal,");
            SQL.AppendLine("               AplicarPromocion = @AplicarPromocion,");
            SQL.AppendLine("               RealizoCierreX = @RealizoCierreX,");
            SQL.AppendLine("               HoraModificacion = @HoraModificacion,");
            SQL.AppendLine("               FormaDeCobro = @FormaDeCobro,");
            SQL.AppendLine("               OtraFormaDeCobro = @OtraFormaDeCobro,");
            SQL.AppendLine("               NoCotizacionDeOrigen = @NoCotizacionDeOrigen,");
            SQL.AppendLine("               NoContrato = @NoContrato,");
            SQL.AppendLine("               ConsecutivoVehiculo = @ConsecutivoVehiculo,");
            SQL.AppendLine("               ConsecutivoAlmacen = @ConsecutivoAlmacen,");
            SQL.AppendLine("               GeneradaPorNotaEntrega = @GeneradaPorNotaEntrega,");
            SQL.AppendLine("               EmitidaEnFacturaNumero = @EmitidaEnFacturaNumero,");
            SQL.AppendLine("               CodigoMoneda = @CodigoMoneda,");
            SQL.AppendLine("               NumeroParaResumen = @NumeroParaResumen,");
            SQL.AppendLine("               NumeroResumenDiario = @NumeroResumenDiario,");
            SQL.AppendLine("               NoControlDespachoDeOrigen = @NoControlDespachoDeOrigen,");
            SQL.AppendLine("               ImprimeFiscal = @ImprimeFiscal,");
            SQL.AppendLine("               EsDiferida = @EsDiferida,");
            SQL.AppendLine("               EsOriginalmenteDiferida = @EsOriginalmenteDiferida,");
            SQL.AppendLine("               SeContabilizoIvaDiferido = @SeContabilizoIvaDiferido,");
            SQL.AppendLine("               AplicaDecretoIvaEspecial = @AplicaDecretoIvaEspecial,");
            SQL.AppendLine("               EsGeneradaPorPuntoDeVenta = @EsGeneradaPorPuntoDeVenta,");
            SQL.AppendLine("               CambioMostrarTotalEnDivisas = @CambioMostrarTotalEnDivisas,");
            SQL.AppendLine("               CodigoMonedaDeCobro = @CodigoMonedaDeCobro,");
            SQL.AppendLine("               NombreOperador = @NombreOperador,");
            SQL.AppendLine("               NroDiasMantenerCambioAMonedaLocal = @NroDiasMantenerCambioAMonedaLocal,");
            SQL.AppendLine("               FechaLimiteCambioAMonedaLocal = @FechaLimiteCambioAMonedaLocal,");
            SQL.AppendLine("               FechaUltimaModificacion = @FechaUltimaModificacion");
            SQL.AppendLine("            WHERE fldTimeStamp = @CurrentTimeStamp");
            SQL.AppendLine("               AND ConsecutivoCompania = @ConsecutivoCompania");
            SQL.AppendLine("               AND Numero = @Numero");
            SQL.AppendLine("               AND TipoDeDocumento = @TipoDeDocumento");
            SQL.AppendLine("         SET @ReturnValue = @@ROWCOUNT");
            SQL.AppendLine("         IF @@ERROR = 0");
            SQL.AppendLine("         BEGIN");
            SQL.AppendLine("            COMMIT TRAN");
            SQL.AppendLine("            IF @ReturnValue = 0");
            SQL.AppendLine("               RAISERROR('El registro ha sido modificado o eliminado por otro usuario', 14, 1)");
            SQL.AppendLine("         END");
            SQL.AppendLine("         ELSE");
            SQL.AppendLine("         BEGIN");
            SQL.AppendLine("            SET @ReturnValue = -1");
            SQL.AppendLine("            SET @ValidationMsg = 'Se ha producido un error al Modificar: ' + CAST(@@ERROR AS NVARCHAR(8))");
            SQL.AppendLine("            RAISERROR(@ValidationMsg, 14 ,1)");
            SQL.AppendLine("            ROLLBACK");
            SQL.AppendLine("         END");
            //SQL.AppendLine("--END");
            //SQL.AppendLine("--ELSE");
            //SQL.AppendLine("--	RAISERROR('El registro no puede ser modificado: %s', 14, 1, @ValidationMsg)");
            SQL.AppendLine("      END");
            SQL.AppendLine("      ELSE");
            SQL.AppendLine("         RAISERROR('El registro ha sido modificado o eliminado por otro usuario.', 14, 1)");
            SQL.AppendLine("   END");
            SQL.AppendLine("   ELSE");
            SQL.AppendLine("      RAISERROR('El registro no existe.', 14, 1)");
            SQL.AppendLine("   RETURN @ReturnValue");
            SQL.AppendLine("END");
            return SQL.ToString();
        }

        private string SqlSpDelParameters() {
            StringBuilder SQL = new StringBuilder();
            //SQL.AppendLine("@ConsecutivoCompania" + InsSql.NumericTypeForDb(10, 0) + ",");
            //SQL.AppendLine("@Numero" + InsSql.VarCharTypeForDb(11) + ",");
            //SQL.AppendLine("@TipoDeDocumento" + InsSql.CharTypeForDb(1) + ",");
            //SQL.AppendLine("@TimeStampAsInt" + InsSql.BigintTypeForDb());
            return SQL.ToString();
        }

        private string SqlSpDel() {
            StringBuilder SQL = new StringBuilder();
            //SQL.AppendLine("BEGIN");
            //SQL.AppendLine("   SET NOCOUNT ON;");
            //SQL.AppendLine("   DECLARE @CurrentTimeStamp timestamp");
            //SQL.AppendLine("   DECLARE @ValidationMsg " + InsSql.VarCharTypeForDb(1500) + " --No puede ser más");
            //SQL.AppendLine("   DECLARE @ReturnValue " + InsSql.NumericTypeForDb(10, 0) + "");
            ////SQL.AppendLine("--DECLARE @CanBeDeleted bit");
            //SQL.AppendLine("   SET @ReturnValue = -1");
            //SQL.AppendLine("   SET @ValidationMsg = ''");
            //SQL.AppendLine("   IF EXISTS(SELECT ConsecutivoCompania FROM dbo.Factura WHERE ConsecutivoCompania = @ConsecutivoCompania AND Numero = @Numero AND TipoDeDocumento = @TipoDeDocumento)");
            //SQL.AppendLine("   BEGIN");
            //SQL.AppendLine("      SELECT @CurrentTimeStamp = fldTimeStamp FROM dbo.Factura WHERE ConsecutivoCompania = @ConsecutivoCompania AND Numero = @Numero AND TipoDeDocumento = @TipoDeDocumento");
            //SQL.AppendLine("      IF (CAST(@CurrentTimeStamp AS bigint) = @TimeStampAsInt)");
            //SQL.AppendLine("      BEGIN");
            //SQL.AppendLine("--Para Validaciones de FK Lógicas crear e invocar:DECLARE @CanBeDeleted bit; EXEC @CanBeDeleted = dbo.Gp_FacturacionRapidaCanBeDeleted @ConsecutivoCompania,@Numero,@TipoDeDocumento, @CurrentTimeStamp, @ValidationMsg out");
            ////SQL.AppendLine("--IF @CanBeDeleted = 1 --True");
            ////SQL.AppendLine("--BEGIN");
            //SQL.AppendLine("         BEGIN TRAN");
            //SQL.AppendLine("         DELETE FROM dbo.Factura");
            //SQL.AppendLine("            WHERE fldTimeStamp = @CurrentTimeStamp");
            //SQL.AppendLine("               AND ConsecutivoCompania = @ConsecutivoCompania");
            //SQL.AppendLine("               AND Numero = @Numero");
            //SQL.AppendLine("               AND TipoDeDocumento = @TipoDeDocumento");
            //SQL.AppendLine("         SET @ReturnValue = @@ROWCOUNT");
            //SQL.AppendLine("         IF @@ERROR = 0");
            //SQL.AppendLine("         BEGIN");
            //SQL.AppendLine("            COMMIT TRAN");
            //SQL.AppendLine("            IF @ReturnValue = 0");
            //SQL.AppendLine("               RAISERROR('El registro ha sido modificado o eliminado por otro usuario', 14, 1)");
            //SQL.AppendLine("         END");
            //SQL.AppendLine("         ELSE");
            //SQL.AppendLine("         BEGIN");
            //SQL.AppendLine("            SET @ReturnValue = -1");
            //SQL.AppendLine("            SET @ValidationMsg = 'Se ha producido un error al Eliminar: ' + CAST(@@ERROR AS NVARCHAR(8))");
            //SQL.AppendLine("            RAISERROR(@ValidationMsg, 14 ,1)");
            //SQL.AppendLine("            ROLLBACK");
            //SQL.AppendLine("         END");
            ////SQL.AppendLine("--END");
            ////SQL.AppendLine("--ELSE");
            ////SQL.AppendLine("--	RAISERROR('El registro no puede ser eliminado: %s', 14, 1, @ValidationMsg)");
            //SQL.AppendLine("      END");
            //SQL.AppendLine("      ELSE");
            //SQL.AppendLine("         RAISERROR('El registro ha sido modificado o eliminado por otro usuario.', 14, 1)");
            //SQL.AppendLine("   END");
            //SQL.AppendLine("   ELSE");
            //SQL.AppendLine("      RAISERROR('El registro no existe.', 14, 1)");
            //SQL.AppendLine("   RETURN @ReturnValue");
            //SQL.AppendLine("END");
            return SQL.ToString();
        }

        private string SqlSpGetParameters() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("@ConsecutivoCompania" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@Numero" + InsSql.VarCharTypeForDb(11) + ",");
            SQL.AppendLine("@TipoDeDocumento" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@StatusFactura" + InsSql.CharTypeForDb(1));
            return SQL.ToString();
        }

        private string SqlSpGet() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("BEGIN");
            SQL.AppendLine("   SET NOCOUNT ON;");
            SQL.AppendLine("   SELECT ");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.ConsecutivoCompania,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.Numero,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.Fecha,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.CodigoCliente,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.NumeroRIF,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.NombreCliente,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.CodigoVendedor,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.NombreVendedor,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.TotalMontoExento,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.TotalBaseImponible,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.TotalRenglones,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.TotalIVA,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.TotalFactura,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.PorcentajeDescuento,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.Moneda,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.NivelDePrecio,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.StatusFactura,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.TipoDeDocumento,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.MontoIvaRetenido,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.FechaAplicacionRetIVA,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.FacturaConPreciosSinIva,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.ConsecutivoCaja,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.GeneraCobroDirecto,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.PorcentajeAlicuota1,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.PorcentajeAlicuota2,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.PorcentajeAlicuota3,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.MontoIvaAlicuota2,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.MontoIvaAlicuota1,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.MontoIvaAlicuota3,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.MontoGravableAlicuota1,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.MontoGravableAlicuota2,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.MontoGravableAlicuota3,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.ConsecutivoAlmacen,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.CambioABolivares,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.ConsecutivoCaja,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.ImprimeFiscal,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.AplicaDecretoIvaEspecial,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.EsGeneradaPorPuntoDeVenta,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.CambioMostrarTotalEnDivisas,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.CodigoMonedaDeCobro,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.NombreMonedaDeCobro,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.CodigoMoneda,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.NombreOperador,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.NroDiasMantenerCambioAMonedaLocal,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.FechaLimiteCambioAMonedaLocal,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.FechaUltimaModificacion,");
            SQL.AppendLine("         CAST(" + DbSchema + ".Gv_FacturaRapida_B1.fldTimeStamp AS bigint) AS fldTimeStampBigint,");
            SQL.AppendLine("         " + DbSchema + ".Gv_FacturaRapida_B1.fldTimeStamp");
            SQL.AppendLine("      FROM " + DbSchema + ".Gv_FacturaRapida_B1");
            SQL.AppendLine("      WHERE " + DbSchema + ".Gv_FacturaRapida_B1.ConsecutivoCompania = @ConsecutivoCompania");
            SQL.AppendLine("         AND " + DbSchema + ".Gv_FacturaRapida_B1.Numero = @Numero");
            SQL.AppendLine("         AND " + DbSchema + ".Gv_FacturaRapida_B1.TipoDeDocumento = @TipoDeDocumento");
            SQL.AppendLine("         AND " + DbSchema + ".Gv_FacturaRapida_B1.StatusFactura = @StatusFactura");
            SQL.AppendLine("   RETURN @@ROWCOUNT");
            SQL.AppendLine("END");
            return SQL.ToString();
        }

        private string SqlSpSearchParameters() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("@SQLWhere" + InsSql.VarCharTypeForDb(2000) + " = null,");
            SQL.AppendLine("@SQLOrderBy" + InsSql.VarCharTypeForDb(500) + " = null,");
            SQL.AppendLine("@DateFormat" + InsSql.VarCharTypeForDb(3) + " = null,");
            SQL.AppendLine("@UseTopClausule" + InsSql.VarCharTypeForDb(1) + " = 'S'");
            return SQL.ToString();
        }

        private string SqlSpSearch() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("BEGIN");
            SQL.AppendLine("   SET NOCOUNT ON;");
            SQL.AppendLine("   DECLARE @strSQL AS " + InsSql.VarCharTypeForDb(7000));
            SQL.AppendLine("   DECLARE @TopClausule AS " + InsSql.VarCharTypeForDb(10));
            SQL.AppendLine("   IF(@UseTopClausule = 'S') ");
            SQL.AppendLine("    SET @TopClausule = 'TOP 500'");
            SQL.AppendLine("   ELSE ");
            SQL.AppendLine("    SET @TopClausule = ''");
            SQL.AppendLine("   SET @strSQL = ");
            SQL.AppendLine("    ' SET DateFormat ' + @DateFormat + ");
            SQL.AppendLine("    ' SELECT ' + @TopClausule + '");
            SQL.AppendLine("      " + DbSchema + ".Gv_FacturaRapida_B1.Numero");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.Fecha");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.CodigoCliente");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.NumeroRIF");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.NombreCliente");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.TotalFactura");
            SQL.AppendLine("      ,''COLPIVOTE'' AS ColControl ");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.ConsecutivoCompania");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.CodigoVendedor");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.TotalMontoExento");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.TotalBaseImponible");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.TotalRenglones");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.TotalIVA");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.PorcentajeDescuento");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.Moneda");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.NivelDePrecio");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.StatusFactura");
			SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.CodigoAlmacen");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.StatusFacturaStr");
			SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.TipoDeDocumento");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.TipoDeDocumentoStr");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.MontoIvaRetenido");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.FechaAplicacionRetIVA");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.FacturaConPreciosSinIva");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.ConsecutivoCaja");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.GeneraCobroDirecto");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.PorcentajeAlicuota1");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.PorcentajeAlicuota2");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.PorcentajeAlicuota3");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.MontoIvaAlicuota2");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.MontoIvaAlicuota1");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.MontoIvaAlicuota3");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.MontoGravableAlicuota1");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.MontoGravableAlicuota2");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.MontoGravableAlicuota3");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.ConsecutivoAlmacen");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.CambioABolivares");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.CambioMostrarTotalEnDivisas");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.CodigoMonedaDeCobro");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.NombreMonedaDeCobro");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.NumeroControl");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.ConsecutivoCaja");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.CodigoMoneda");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.NombreVendedor");
            SQL.AppendLine("      ," + DbSchema + ".Gv_FacturaRapida_B1.NombreOperador");
            SQL.AppendLine("      FROM " + DbSchema + ".Gv_FacturaRapida_B1");
            //SQL.AppendLine("      INNER JOIN dbo.Gv_Caja_B1 ON  " + DbSchema + ".Gv_FacturaRapida_B1.ConsecutivoCaja = dbo.Gv_Caja_B1.ConsecutivoCaja");
            //SQL.AppendLine("      AND " + DbSchema + ".Gv_FacturaRapida_B1.ConsecutivoCompania = dbo.Gv_Caja_B1.ConsecutivoCompania");
            SQL.AppendLine("'   IF (NOT @SQLWhere IS NULL) AND (@SQLWhere <> '')");
            SQL.AppendLine("      SET @strSQL = @strSQL + ' WHERE ' + @SQLWhere");
            SQL.AppendLine("   IF (NOT @SQLOrderBy IS NULL) AND (@SQLOrderBy <> '')");
            SQL.AppendLine("      SET @strSQL = @strSQL + ' ORDER BY ' + @SQLOrderBy");
            SQL.AppendLine("   EXEC(@strSQL)");
            SQL.AppendLine("END");
            return SQL.ToString();
        }

        private string SqlSpGetFKParameters() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("@ConsecutivoCompania" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@XmlData" + InsSql.XmlTypeForDb());
            return SQL.ToString();
        }

        private string SqlSpGetFK() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("BEGIN");
            SQL.AppendLine(" DECLARE @hdoc int ");
            SQL.AppendLine(" EXEC sp_xml_preparedocument @hdoc OUTPUT, @XmlData ");
            SQL.AppendLine("   SET NOCOUNT ON;");
            SQL.AppendLine("   SELECT ");
            SQL.AppendLine("      dbo.Factura.ConsecutivoCompania,");
            SQL.AppendLine("      dbo.Factura.Numero,");
            SQL.AppendLine("      dbo.Factura.Fecha,");
            SQL.AppendLine("      dbo.Factura.CodigoVendedor,");
            SQL.AppendLine("      dbo.Factura.ConsecutivoCaja,");
            SQL.AppendLine("      dbo.Factura.NumeroComprobanteFiscal,");
            SQL.AppendLine("      dbo.Factura.TipoDeDocumento");
            //SQL.AppendLine("      ,dbo.Factura.[Programador - personaliza este sp y coloca solo los campos que te interesa exponer a quienes lo consumen]");
            SQL.AppendLine("      FROM dbo.Factura");
            SQL.AppendLine("      WHERE ConsecutivoCompania = @ConsecutivoCompania");
            SQL.AppendLine("          AND TipoDeDocumento IN (");
            SQL.AppendLine("            SELECT  TipoDeDocumento ");
            SQL.AppendLine("            FROM OPENXML( @hdoc, 'GpData/GpResult',2) ");
            SQL.AppendLine("            WITH (TipoDeDocumento char(1)) AS XmlDocOfFK) ");
            SQL.AppendLine(" EXEC sp_xml_removedocument @hdoc");
            SQL.AppendLine("   RETURN @@ROWCOUNT");
            SQL.AppendLine("END");
            return SQL.ToString();
        }


        private string SqlSpFacturaGeneraProximoNumeroParameters() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("@ConsecutivoCompania" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@StatusFactura" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@TipoDeDocumento" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@PrefijoFactura" + InsSql.VarCharTypeForDb(11) + ",");
            SQL.AppendLine("@NroCerosAlaIzquiera " + InsSql.NumericTypeForDb(11,0));
            return SQL.ToString();
        }

        private string SqlSpFacturaGeneraProximoNumero() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine(" BEGIN ");
            SQL.AppendLine(" DECLARE @LongitudParaElCorte int ");
            SQL.AppendLine(" , @PrefijoFinal VARCHAR(11) ");
            SQL.AppendLine(" SET NOCOUNT ON; ");
            SQL.AppendLine(" SELECT @LongitudParaElCorte = ");
            SQL.AppendLine(" @NroCerosAlaIzquiera  ");
            SQL.AppendLine(" - (LEN(@PrefijoFactura)  + LEN(CAST( SUBSTRING(ISNULL(MAX(Numero),0), LEN(@PrefijoFactura) + 1, @NroCerosAlaIzquiera) + 1  AS VARCHAR))) ");
            SQL.AppendLine(" FROM  ");
            SQL.AppendLine(" Factura ");
            SQL.AppendLine(" WHERE  ");
            SQL.AppendLine(" ConsecutivoCompania = @ConsecutivoCompania ");
            SQL.AppendLine(" AND TipoDeDocumento = @TipoDeDocumento ");
            SQL.AppendLine(" AND StatusFactura = @StatusFactura ");
            SQL.AppendLine(" AND Numero LIKE @PrefijoFactura + '%' ");
            SQL.AppendLine(" 	IF (@LongitudParaElCorte < @NroCerosAlaIzquiera) AND @NroCerosAlaIzquiera >= 10 ");
            SQL.AppendLine(" 	   SELECT @PrefijoFinal=  @PrefijoFactura + RIGHT('00000000000', @LongitudParaElCorte) ");
            SQL.AppendLine(" 	ELSE ");
            SQL.AppendLine(" 	   BEGIN ");
            SQL.AppendLine(" 		 IF  (@LongitudParaElCorte < @NroCerosAlaIzquiera) AND @NroCerosAlaIzquiera < 10 AND @StatusFactura = '0' ");
            SQL.AppendLine(" 		    SELECT @PrefijoFinal=  @PrefijoFactura + RIGHT('00000000000', @NroCerosAlaIzquiera - @LongitudParaElCorte) ");
            SQL.AppendLine(" 		 ELSE IF @StatusFactura = '2' ");
            SQL.AppendLine(" 		    SELECT @PrefijoFinal=  @PrefijoFactura + RIGHT('00000000000', @LongitudParaElCorte) ");
            SQL.AppendLine(" 		 ELSE  ");
            SQL.AppendLine(" 		   SELECT @PrefijoFinal=  @PrefijoFactura ");
            SQL.AppendLine(" 	   END ");
            SQL.AppendLine(" IF @StatusFactura = '0' ");
            SQL.AppendLine("  BEGIN ");
            SQL.AppendLine(" 	 	SELECT  ");
            SQL.AppendLine(" 	 	 	@PrefijoFinal ");
            SQL.AppendLine(" 	 	 	+ CAST( SUBSTRING(ISNULL(MAX(Numero),0), LEN(@PrefijoFactura) + 1, 11) + 1  AS VARCHAR(11)) AS Numero ");
            SQL.AppendLine("  	 	FROM  ");
            SQL.AppendLine(" 	 	 	dbo.factura ");
            SQL.AppendLine("  	 	WHERE  ");
            SQL.AppendLine("      	 	ConsecutivoCompania = @ConsecutivoCompania ");
            SQL.AppendLine(" 	 	 	AND TipoDeDocumento = @TipoDeDocumento ");
            SQL.AppendLine(" 	 	 	AND (StatusFactura = '0' OR StatusFactura = '1') ");
            SQL.AppendLine(" 	 	 	AND Numero LIKE @PrefijoFactura + '%' ");
            SQL.AppendLine("  END ");
            SQL.AppendLine("ELSE  ");
            SQL.AppendLine("  BEGIN ");
            SQL.AppendLine(" 	 	SELECT  ");
            SQL.AppendLine(" 	 	 	@PrefijoFinal ");
            SQL.AppendLine(" 	 	 	+ CAST( SUBSTRING(ISNULL(MAX(Numero),0), LEN(@PrefijoFactura) + 1, 11) + 1  AS VARCHAR(11)) AS Numero ");
            SQL.AppendLine("  	 	FROM  ");
            SQL.AppendLine(" 	 	 	dbo.factura ");
            SQL.AppendLine("  	 	WHERE  ");
            SQL.AppendLine("      	 	ConsecutivoCompania = @ConsecutivoCompania ");
            SQL.AppendLine(" 	 	 	AND TipoDeDocumento = @TipoDeDocumento ");
            SQL.AppendLine(" 	 	 	AND StatusFactura = @StatusFactura ");
            SQL.AppendLine(" 	 	 	AND Numero LIKE @PrefijoFactura + '%' ");
            SQL.AppendLine("   END ");
            SQL.AppendLine(" END ");
            return SQL.ToString();
        }


        #endregion //Queries

        bool CrearTabla() {
            //bool vResult = insDbo.Create(DbSchema + ".Factura", SqlCreateTable(), false, eDboType.Tabla);
            return true;
        }

        bool CrearVistas(){
            bool vResult = false;
            LibViews insVistas = new LibViews();
            vResult = insVistas.Create(DbSchema + ".Gv_EnumStatusFactura", LibTpvCreator.SqlViewStandardEnum(typeof(eStatusFactura), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_EnumTipoDocumentoFactura", LibTpvCreator.SqlViewStandardEnum(typeof(eTipoDocumentoFactura), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_EnumFormaDeLaInicial", LibTpvCreator.SqlViewStandardEnum(typeof(eFormaDeLaInicial), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_EnumTalonario", LibTpvCreator.SqlViewStandardEnum(typeof(eTalonario), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_EnumFormadePago", LibTpvCreator.SqlViewStandardEnum(typeof(eFormadePago), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_EnumTipoDeTransaccionDeLibrosFiscales", LibTpvCreator.SqlViewStandardEnum(typeof(eTipoDeTransaccionDeLibrosFiscales), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_EnumTipoDeVenta", LibTpvCreator.SqlViewStandardEnum(typeof(eTipoDeVenta), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_EnumTipoDeFormaDeCobro", LibTpvCreator.SqlViewStandardEnum(typeof(eTipoDeFormaDeCobro), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_FacturaRapida_B1", SqlViewB1(), true);
            insVistas.Dispose();
            return vResult;
        }

        bool CrearProcedimientos() {
            bool vResult = false;
            LibStoredProc insSps = new LibStoredProc();
            vResult = insSps.CreateStoredProcedure(DbSchema + ".Gp_FacturaRapidaINS", SqlSpInsParameters(), SqlSpIns(), true);
            vResult = insSps.CreateStoredProcedure(DbSchema + ".Gp_FacturaRapidaUPD", SqlSpUpdParameters(), SqlSpUpd(), true);
            //LibFile.WriteLineInFile(@"C:\prueba.txt", "Gp_FacturaRapidaINS : " + vResult);
            vResult = insSps.CreateStoredProcedure(DbSchema + ".Gp_FacturaRapidaGET", SqlSpGetParameters(), SqlSpGet(), true) && vResult;
            vResult = insSps.CreateStoredProcedure(DbSchema + ".Gp_FacturaRapidaSCH", SqlSpSearchParameters(), SqlSpSearch(), true) && vResult;
            vResult = insSps.CreateStoredProcedure(DbSchema + ".Gp_FacturaRapidaGetFk", SqlSpGetFKParameters(), SqlSpGetFK(), true) && vResult;
            vResult = insSps.CreateStoredProcedure(DbSchema + ".Gp_FacturaGeneraProximoNumero", SqlSpFacturaGeneraProximoNumeroParameters(), SqlSpFacturaGeneraProximoNumero(), true) && vResult;
            insSps.Dispose();
            return vResult;
        }

        public bool InstalarTabla() {
            bool vResult = true;
            //if (CrearTabla()) {
            CrearVistas();
            CrearProcedimientos();
            //clsRenglonFacturaED insDetailFacRapDet = new clsRenglonFacturaED();
            //vResult = insDetailFacRapDet.InstalarTabla();
            //}
            return vResult;
        }

        public bool InstalarVistasYSps() {
            bool vResult = true;
            //if (insDbo.Exists(DbSchema + ".Factura", eDboType.Tabla)) {
                CrearVistas();
                CrearProcedimientos();
                vResult = new clsRenglonFacturaED().InstalarVistasYSps();
            //}
            return vResult;
        }

        public bool BorrarVistasYSps() {
            bool vResult = false;
            LibStoredProc insSp = new LibStoredProc();
            LibViews insVista = new LibViews();
            vResult = new clsRenglonFacturaED().BorrarVistasYSps();
            vResult = insSp.Drop(DbSchema + ".Gp_FacturaGeneraProximoNumero") && vResult;
            vResult = insSp.Drop(DbSchema + ".Gp_FacturaRapidaINS") && vResult;
            vResult = insSp.Drop(DbSchema + ".Gp_FacturaRapidaUPD") && vResult;
            //vResult = insSp.Drop(DbSchema + ".Gp_FacturacionRapidaDEL") && vResult;
            vResult = insSp.Drop(DbSchema + ".Gp_FacturaRapidaGET") && vResult;
            vResult = insSp.Drop(DbSchema + ".Gp_FacturaRapidaGetFk") && vResult;
            vResult = insSp.Drop(DbSchema + ".Gp_FacturaRapidaSCH") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_FacturaRapida_B1") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumStatusFactura") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumTipoDocumentoFactura") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumFormaDeLaInicial") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumTalonario") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumFormadePago") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumTipoDeTransaccionDeLibrosFiscales") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumTipoDeVenta") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumTipoDeFormaDeCobro") && vResult;
            insSp.Dispose();
            insVista.Dispose();
            return vResult;
        }
        #endregion //Metodos Generados


    } //End of class clsFacturaRapidaED

} //End of namespace Galac.Adm.Dal.Venta

