using System;
using System.Collections.Generic;
using System.Text;
using LibGalac.Aos.Dal;
using Galac.Adm.Ccl.CajaChica;
using Galac.Adm.Ccl.Banco;

namespace Galac.Adm.Dal.CajaChica {
    public class clsCxPED: LibED {
        #region Variables
        #endregion //Variables
        #region Propiedades
        #endregion //Propiedades
        #region Constructores
        public clsCxPED(): base(){
            DbSchema = "dbo";
        }
        #endregion //Constructores
        #region Metodos Generados
        #region Queries

        private string SqlCreateTable() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine(InsSql.CreateTable("CxP", DbSchema) + " ( ");
            SQL.AppendLine("ConsecutivoCompania" + InsSql.NumericTypeForDb(10, 0) + " CONSTRAINT nnCxPConsecutiv NOT NULL, ");
            SQL.AppendLine("Numero" + InsSql.VarCharTypeForDb(11) + " CONSTRAINT nnCxPNumero NOT NULL, ");
            SQL.AppendLine("ConsecutivoCxP" + InsSql.NumericTypeForDb(10, 0) + " CONSTRAINT nnCxPConsecutiv NOT NULL, ");
            SQL.AppendLine("TipoDeCxP" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_CxPTiDeCxP DEFAULT ('0'), ");
            SQL.AppendLine("Status" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_CxPSt DEFAULT ('0'), ");
            SQL.AppendLine("CodigoProveedor" + InsSql.VarCharTypeForDb(10) + " CONSTRAINT nnCxPCodigoProv NOT NULL, ");
            SQL.AppendLine("Fecha" + InsSql.DateTypeForDb() + " CONSTRAINT d_CxPFe DEFAULT (''), ");
            SQL.AppendLine("FechaCancelacion" + InsSql.DateTypeForDb() + " CONSTRAINT d_CxPFeCa DEFAULT (''), ");
            SQL.AppendLine("FechaVencimiento" + InsSql.DateTypeForDb() + " CONSTRAINT d_CxPFeVe DEFAULT (''), ");
            SQL.AppendLine("FechaAnulacion" + InsSql.DateTypeForDb() + " CONSTRAINT d_CxPFeAn DEFAULT (''), ");
            SQL.AppendLine("CodigoMoneda" + InsSql.VarCharTypeForDb(4) + " CONSTRAINT d_CxPCoMo DEFAULT (''), ");
            SQL.AppendLine("Moneda" + InsSql.VarCharTypeForDb(10) + " CONSTRAINT d_CxPMo DEFAULT (''), ");
            SQL.AppendLine("CambioABolivares" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPCaAB DEFAULT (0), ");
            SQL.AppendLine("AplicaParaLibrodeCompras" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPAplicaPara NOT NULL, ");
            SQL.AppendLine("MontoExento" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoEx DEFAULT (0), ");
            SQL.AppendLine("MontoGravado" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoGr DEFAULT (0), ");
            SQL.AppendLine("MontoIva" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoIv DEFAULT (0), ");
            SQL.AppendLine("MontoAbonado" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoAb DEFAULT (0), ");
            SQL.AppendLine("DiaDeAplicacion" + InsSql.NumericTypeForDb(10,0) + " CONSTRAINT d_CxPDiDeAp DEFAULT (0), ");
            SQL.AppendLine("MesDeAplicacion" + InsSql.NumericTypeForDb(10, 0) + " CONSTRAINT d_CxPMeDeAp DEFAULT (0), ");
            SQL.AppendLine("AnoDeAplicacion" + InsSql.NumericTypeForDb(10, 0) + " CONSTRAINT d_CxPAnDeAp DEFAULT (0), ");
            SQL.AppendLine("Observaciones" + InsSql.VarCharTypeForDb(255) + " CONSTRAINT d_CxPOb DEFAULT (''), ");
            SQL.AppendLine("CreditoFiscal" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_CxPCrFi DEFAULT ('0'), ");
            SQL.AppendLine("TipoDeCompra" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_CxPTiDeCo DEFAULT ('0'), ");
            SQL.AppendLine("SeHizoLaRetencion" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPSeHizoLaRe NOT NULL, ");
            SQL.AppendLine("MontoGravableAlicuotaGeneral" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoGrAlGe DEFAULT (0), ");
            SQL.AppendLine("MontoGravableAlicuota2" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoGrAl2 DEFAULT (0), ");
            SQL.AppendLine("MontoGravableAlicuota3" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoGrAl3 DEFAULT (0), ");
            SQL.AppendLine("MontoIVAAlicuotaGeneral" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoIVGe DEFAULT (0), ");
            SQL.AppendLine("MontoIVAAlicuota2" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoIV2 DEFAULT (0), ");
            SQL.AppendLine("MontoIVAAlicuota3" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoIV3 DEFAULT (0), ");
            SQL.AppendLine("NumeroPlanillaDeImportacion" + InsSql.VarCharTypeForDb(20) + " CONSTRAINT d_CxPNuPlDeIm DEFAULT (''), ");
            SQL.AppendLine("NumeroExpedienteDeImportacion" + InsSql.VarCharTypeForDb(20) + " CONSTRAINT d_CxPNuExDeIm DEFAULT (''), ");
            SQL.AppendLine("TipoDeTransaccion" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_CxPTiDeTr DEFAULT ('0'), ");
            SQL.AppendLine("NumeroDeFacturaAfectada" + InsSql.VarCharTypeForDb(11) + " CONSTRAINT d_CxPNuDeFaAf DEFAULT (''), ");
            SQL.AppendLine("NumeroControl" + InsSql.VarCharTypeForDb(20) + " CONSTRAINT d_CxPNuCo DEFAULT (''), ");
            SQL.AppendLine("SeHizoLaRetencionIVA" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPSeHizoLaRe NOT NULL, ");
            SQL.AppendLine("NumeroComprobanteRetencion" + InsSql.VarCharTypeForDb(8) + " CONSTRAINT d_CxPNuCoRe DEFAULT (''), ");
            SQL.AppendLine("FechaAplicacionRetIVA" + InsSql.DateTypeForDb() + " CONSTRAINT d_CxPFeApReIV DEFAULT (''), ");
            SQL.AppendLine("PorcentajeRetencionAplicado" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPPoReAp DEFAULT (0), ");
            SQL.AppendLine("MontoRetenido" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoRe DEFAULT (0), ");
            SQL.AppendLine("OrigenDeLaRetencion" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_CxPOrDeLaRe DEFAULT ('0'), ");
            SQL.AppendLine("RetencionAplicadaEnPago" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPRetencionA NOT NULL, ");
            SQL.AppendLine("OrigenInformacionRetencion" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_CxPOrInRe DEFAULT ('0'), ");
            SQL.AppendLine("CxPgeneradaPor" + InsSql.CharTypeForDb(1) + " CONSTRAINT d_CxPCxPgPo DEFAULT ('0'), ");
            SQL.AppendLine("EsCxPhistorica" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPEsCxPhisto NOT NULL, ");
            SQL.AppendLine("NumDiasDeVencimiento" + InsSql.NumericTypeForDb(10, 0) + " CONSTRAINT d_CxPNuDiDeVe DEFAULT (0), ");
            SQL.AppendLine("NumeroDocOrigen" + InsSql.VarCharTypeForDb(15) + " CONSTRAINT d_CxPNuDoOr DEFAULT (''), ");
            SQL.AppendLine("CodigoLote" + InsSql.VarCharTypeForDb(10) + " CONSTRAINT d_CxPCoLo DEFAULT (''), ");
            SQL.AppendLine("GenerarAsientoDeRetiroEnCuenta" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPGenerarAsi NOT NULL, ");
            SQL.AppendLine("TotalOtrosImpuestos" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPToOtIm DEFAULT (0), ");
            SQL.AppendLine("SeContabilRetIva" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPSeContabil NOT NULL, ");
            SQL.AppendLine("DondeContabilRetIva" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPDondeConta NOT NULL, ");
            SQL.AppendLine("OrigenDeLaRetencionISLR" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPOrigenDeLa NOT NULL, ");
            SQL.AppendLine("DondeContabilISLR" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPDondeConta NOT NULL, ");
            SQL.AppendLine("ISLRAplicadaEnPago" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPISLRAplica NOT NULL, ");
            SQL.AppendLine("MontoRetenidoISLR" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoReIS DEFAULT (0), ");
            SQL.AppendLine("SeContabilISLR" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPSeContabil NOT NULL, ");
            SQL.AppendLine("FechaAplicacionImpuestoMunicipal" + InsSql.DateTypeForDb() + " CONSTRAINT nnCxPFechaAplic NOT NULL, ");
            SQL.AppendLine("NumeroComprobanteImpuestoMunicipal" + InsSql.VarCharTypeForDb(50) + " CONSTRAINT d_CxPNuCoImMu DEFAULT (''), ");
            SQL.AppendLine("MontoRetenidoImpuestoMunicipal" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoReImMu DEFAULT (0), ");
            SQL.AppendLine("ImpuestoMunicipalRetenido" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPImpuestoMu NOT NULL, ");
            SQL.AppendLine("NumeroControlDeFacturaAfectada" + InsSql.VarCharTypeForDb(11) + " CONSTRAINT d_CxPNuCoDeFaAf DEFAULT (''), ");
            SQL.AppendLine("ConsecutivoRendicion" + InsSql.NumericTypeForDb(10, 0) + " CONSTRAINT nnCxPConsecutiv NOT NULL, ");
            SQL.AppendLine("EstaAsociadoARendicion" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPEstaAsocia NOT NULL, ");
			SQL.AppendLine("NumeroDeclaracionAduana" + InsSql.VarCharTypeForDb(20) + " CONSTRAINT d_CxPNuDeAd DEFAULT (''), ");
            SQL.AppendLine("FechaDeclaracionAduana" + InsSql.DateTypeForDb() + " CONSTRAINT d_CxPFeDeAd DEFAULT (''), ");
            SQL.AppendLine("UsaPrefijoSerie" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPUsaPrefijo NOT NULL, ");
            SQL.AppendLine("CodigoProveedorOriginalServicio" + InsSql.VarCharTypeForDb(10) + ", ");
            SQL.AppendLine("EsUnaCuentaATerceros" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnEsUnaCuentaA NOT NULL, ");
            SQL.AppendLine("SeHizoLaDetraccion" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPSeHizoLaDe NOT NULL, ");
            SQL.AppendLine("AplicaIvaAlicuotaEspecial" + InsSql.CharTypeForDb(1) + " CONSTRAINT nnCxPAplicaIvaA NOT NULL, ");
            SQL.AppendLine("MontoGravableAlicuotaEspecial1" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoGrAlEs1 DEFAULT (0), ");
            SQL.AppendLine("MontoIVAAlicuotaEspecial1" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoIVEs1 DEFAULT (0), ");
            SQL.AppendLine("PorcentajeIvaAlicuotaEspecial1" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPPoIvAlEs1 DEFAULT (0), ");
            SQL.AppendLine("MontoGravableAlicuotaEspecial2" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoGrAlEs2 DEFAULT (0), ");
            SQL.AppendLine("MontoIVAAlicuotaEspecial2" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoIVEs2 DEFAULT (0), ");
            SQL.AppendLine("PorcentajeIvaAlicuotaEspecial2" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPPoIvAlEs2 DEFAULT (0), ");
            SQL.AppendLine("BaseImponibleIGTFML" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPBaImIG DEFAULT (0), ");
            SQL.AppendLine("AlicuotaIGTFML" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPAlIG DEFAULT (0), ");
            SQL.AppendLine("MontoIGTFML" + InsSql.DecimalTypeForDb(25, 4) + " CONSTRAINT d_CxPMoIG DEFAULT (0), ");
            SQL.AppendLine("NombreOperador" + InsSql.VarCharTypeForDb(20) + ", ");
            SQL.AppendLine("FechaUltimaModificacion" + InsSql.DateTypeForDb() + ", ");
            SQL.AppendLine("fldTimeStamp" + InsSql.TimeStampTypeForDb() + ",");
            SQL.AppendLine("CONSTRAINT p_CxP PRIMARY KEY CLUSTERED");
            SQL.AppendLine("(ConsecutivoCompania ASC, ConsecutivoCxP ASC)");
            SQL.AppendLine(", CONSTRAINT fk_CxPProveedor FOREIGN KEY (ConsecutivoCompania, CodigoProveedor)");
            SQL.AppendLine("REFERENCES dbo.Proveedor(ConsecutivoCompania, codigoProveedor)");
            SQL.AppendLine("ON UPDATE CASCADE");
            SQL.AppendLine(", CONSTRAINT fk_CxPMoneda FOREIGN KEY (CodigoMoneda)");
            SQL.AppendLine("REFERENCES dbo.Moneda(Codigo)");
            SQL.AppendLine("ON UPDATE CASCADE");
            SQL.AppendLine(", CONSTRAINT fk_CxPRendicion FOREIGN KEY (ConsecutivoCompania, ConsecutivoRendicion)");
            SQL.AppendLine("REFERENCES Adm.Rendicion(ConsecutivoCompania, Consecutivo)");
            SQL.AppendLine("ON UPDATE CASCADE");
            SQL.AppendLine(")");
            return SQL.ToString();
        }

        private string SqlViewB1() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("SELECT CxP.ConsecutivoCompania, CxP.Numero, CxP.ConsecutivoCxP, CxP.TipoDeCxP, " + DbSchema + ".Gv_EnumTipoDeCxC.StrValue AS TipoDeCxPStr");
            SQL.AppendLine(", CxP.Status, " + DbSchema + ".Gv_EnumStatusDocumento.StrValue AS StatusStr, CxP.CodigoProveedor, CxP.Fecha, CxP.FechaCancelacion");
            SQL.AppendLine(", CxP.FechaVencimiento, CxP.FechaAnulacion, CxP.CodigoMoneda, CxP.Moneda");
            SQL.AppendLine(", CxP.CambioABolivares, CxP.AplicaParaLibrodeCompras, CxP.MontoExento, CxP.MontoGravado");
            SQL.AppendLine(", CxP.MontoIva, CxP.MontoAbonado, CxP.DiaDeAplicacion, CxP.MesDeAplicacion, CxP.AnoDeAplicacion");
            SQL.AppendLine(", CxP.Observaciones, CxP.CreditoFiscal, " + DbSchema + ".Gv_EnumCreditoFiscal.StrValue AS CreditoFiscalStr, CxP.TipoDeCompra, " + DbSchema + ".Gv_EnumTipoDeCompra.StrValue AS TipoDeCompraStr, CxP.SeHizoLaRetencion");
            SQL.AppendLine(", CxP.MontoGravableAlicuotaGeneral, CxP.MontoGravableAlicuota2, CxP.MontoGravableAlicuota3, CxP.MontoIVAAlicuotaGeneral");
            SQL.AppendLine(", CxP.MontoIVAAlicuota2, CxP.MontoIVAAlicuota3, CxP.NumeroPlanillaDeImportacion, CxP.NumeroExpedienteDeImportacion");
            SQL.AppendLine(", CxP.TipoDeTransaccion, " + DbSchema + ".Gv_EnumTipoDeTransaccionDeLibrosFiscales.StrValue AS TipoDeTransaccionStr, CxP.NumeroDeFacturaAfectada, CxP.NumeroControl, CxP.SeHizoLaRetencionIVA");
            SQL.AppendLine(", CxP.NumeroComprobanteRetencion, CxP.FechaAplicacionRetIVA, CxP.PorcentajeRetencionAplicado, CxP.MontoRetenido");
            SQL.AppendLine(", CxP.OrigenDeLaRetencion, " + DbSchema + ".Gv_EnumDondeSeEfectuaLaRetencionIVA.StrValue AS OrigenDeLaRetencionStr, CxP.RetencionAplicadaEnPago, CxP.OrigenInformacionRetencion, " + DbSchema + ".Gv_EnumTipoDeContribuyenteDelIva.StrValue AS OrigenInformacionRetencionStr, CxP.CxPgeneradaPor, " + DbSchema + ".Gv_EnumGeneradoPor.StrValue AS CxPgeneradaPorStr");
            SQL.AppendLine(", CxP.EsCxPhistorica, CxP.NumDiasDeVencimiento, CxP.NumeroDocOrigen, CxP.CodigoLote");
            SQL.AppendLine(", CxP.GenerarAsientoDeRetiroEnCuenta, CxP.TotalOtrosImpuestos, CxP.SeContabilRetIva, CxP.DondeContabilRetIva");
            SQL.AppendLine(", CxP.OrigenDeLaRetencionISLR, CxP.DondeContabilISLR, CxP.ISLRAplicadaEnPago, CxP.MontoRetenidoISLR");
            SQL.AppendLine(", CxP.SeContabilISLR, CxP.FechaAplicacionImpuestoMunicipal, CxP.NumeroComprobanteImpuestoMunicipal, CxP.MontoRetenidoImpuestoMunicipal");
            SQL.AppendLine(", CxP.ImpuestoMunicipalRetenido, CxP.NumeroControlDeFacturaAfectada, CxP.ConsecutivoRendicion, CxP.EstaAsociadoARendicion, CxP.SeHizoLaDetraccion");
            SQL.AppendLine(", CxP.AplicaIvaAlicuotaEspecial, CxP.CodigoProveedorOriginalServicio, CxP.EsUnaCuentaATerceros");
            SQL.AppendLine(", CxP.BaseImponibleIGTFML, CxP.AlicuotaIGTFML, CxP.MontoIGTFML, CxP.NombreOperador");
            SQL.AppendLine(", CxP.FechaUltimaModificacion, CxP.FechaDeclaracionAduana, CxP.UsaPrefijoSerie");
            SQL.AppendLine(", Adm.Proveedor.nombreProveedor AS NombreProveedor");
            SQL.AppendLine(", CxP.fldTimeStamp, CAST(CxP.fldTimeStamp AS bigint) AS fldTimeStampBigint");
            SQL.AppendLine("FROM " + DbSchema + ".CxP");
            SQL.AppendLine("INNER JOIN " + DbSchema + ".Gv_EnumTipoDeCxC");
            SQL.AppendLine("ON " + DbSchema + ".CxP.TipoDeCxP COLLATE MODERN_SPANISH_CS_AS");
            SQL.AppendLine(" = " + DbSchema + ".Gv_EnumTipoDeCxC.DbValue");
            SQL.AppendLine("INNER JOIN " + DbSchema + ".Gv_EnumStatusDocumento");
            SQL.AppendLine("ON " + DbSchema + ".CxP.Status COLLATE MODERN_SPANISH_CS_AS");
            SQL.AppendLine(" = " + DbSchema + ".Gv_EnumStatusDocumento.DbValue");
            SQL.AppendLine("INNER JOIN " + DbSchema + ".Gv_EnumCreditoFiscal");
            SQL.AppendLine("ON " + DbSchema + ".CxP.CreditoFiscal COLLATE MODERN_SPANISH_CS_AS");
            SQL.AppendLine(" = " + DbSchema + ".Gv_EnumCreditoFiscal.DbValue");
            SQL.AppendLine("INNER JOIN " + DbSchema + ".Gv_EnumTipoDeCompra");
            SQL.AppendLine("ON " + DbSchema + ".CxP.TipoDeCompra COLLATE MODERN_SPANISH_CS_AS");
            SQL.AppendLine(" = " + DbSchema + ".Gv_EnumTipoDeCompra.DbValue");
            SQL.AppendLine("INNER JOIN " + DbSchema + ".Gv_EnumTipoDeTransaccionDeLibrosFiscales");
            SQL.AppendLine("ON " + DbSchema + ".CxP.TipoDeTransaccion COLLATE MODERN_SPANISH_CS_AS");
            SQL.AppendLine(" = " + DbSchema + ".Gv_EnumTipoDeTransaccionDeLibrosFiscales.DbValue");
            SQL.AppendLine("INNER JOIN " + DbSchema + ".Gv_EnumDondeSeEfectuaLaRetencionIVA");
            SQL.AppendLine("ON " + DbSchema + ".CxP.OrigenDeLaRetencion COLLATE MODERN_SPANISH_CS_AS");
            SQL.AppendLine(" = " + DbSchema + ".Gv_EnumDondeSeEfectuaLaRetencionIVA.DbValue");
            SQL.AppendLine("INNER JOIN " + DbSchema + ".Gv_EnumTipoDeContribuyenteDelIva");
            SQL.AppendLine("ON " + DbSchema + ".CxP.OrigenInformacionRetencion COLLATE MODERN_SPANISH_CS_AS");
            SQL.AppendLine(" = " + DbSchema + ".Gv_EnumTipoDeContribuyenteDelIva.DbValue");
            SQL.AppendLine("INNER JOIN " + DbSchema + ".Gv_EnumGeneradoPor");
            SQL.AppendLine("ON " + DbSchema + ".CxP.CxPgeneradaPor COLLATE MODERN_SPANISH_CS_AS");
            SQL.AppendLine(" = " + DbSchema + ".Gv_EnumGeneradoPor.DbValue");
            SQL.AppendLine("INNER JOIN Adm.Proveedor ON  " + DbSchema + ".CxP.CodigoProveedor = Adm.Proveedor.codigoProveedor");
            SQL.AppendLine("      AND " + DbSchema + ".CxP.ConsecutivoCompania = Adm.Proveedor.ConsecutivoCompania");
            SQL.AppendLine("INNER JOIN dbo.Moneda ON  " + DbSchema + ".CxP.CodigoMoneda = dbo.Moneda.Codigo");
            //SQL.AppendLine("INNER JOIN Adm.Rendicion ON  " + DbSchema + ".CxP.ConsecutivoRendicion = Adm.Rendicion.Consecutivo");
            //SQL.AppendLine("      AND " + DbSchema + ".CxP.ConsecutivoCompania = Adm.Rendicion.ConsecutivoCompania");
            return SQL.ToString();
        }

        private string SqlSpInsParameters() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("@DateFormat" + InsSql.VarCharTypeForDb(3) + ",");
            SQL.AppendLine("@ConsecutivoCompania" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@Numero" + InsSql.VarCharTypeForDb(20) + " = '',");
            SQL.AppendLine("@ConsecutivoCxP" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@TipoDeCxP" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@Status" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@CodigoProveedor" + InsSql.VarCharTypeForDb(10) + ",");
            SQL.AppendLine("@Fecha" + InsSql.DateTypeForDb() + " = '01/01/1900',");
            SQL.AppendLine("@FechaCancelacion" + InsSql.DateTypeForDb() + " = '01/01/1900',");
            SQL.AppendLine("@FechaVencimiento" + InsSql.DateTypeForDb() + " = '01/01/1900',");
            SQL.AppendLine("@FechaAnulacion" + InsSql.DateTypeForDb() + " = '01/01/1900',");
            SQL.AppendLine("@Moneda" + InsSql.VarCharTypeForDb(10) + ",");
            SQL.AppendLine("@CambioABolivares" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@AplicaParaLibrodeCompras" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@MontoExento" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoGravado" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoIva" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoAbonado" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@DiaDeAplicacion" + InsSql.NumericTypeForDb(10,0) + " = 0,");
            SQL.AppendLine("@MesDeAplicacion" + InsSql.NumericTypeForDb(10, 0) + " = 0,");
            SQL.AppendLine("@AnoDeAplicacion" + InsSql.NumericTypeForDb(10, 0) + " = 0,");
            SQL.AppendLine("@Observaciones" + InsSql.VarCharTypeForDb(255) + " = '',");
            SQL.AppendLine("@CreditoFiscal" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@TipoDeCompra" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@SeHizoLaRetencion" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@MontoGravableAlicuotaGeneral" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoGravableAlicuota2" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoGravableAlicuota3" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoIVAAlicuotaGeneral" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoIVAAlicuota2" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoIVAAlicuota3" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@NumeroPlanillaDeImportacion" + InsSql.VarCharTypeForDb(20) + " = '',");
            SQL.AppendLine("@NumeroExpedienteDeImportacion" + InsSql.VarCharTypeForDb(20) + " = '',");
            SQL.AppendLine("@TipoDeTransaccion" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@NumeroDeFacturaAfectada" + InsSql.VarCharTypeForDb(11) + " = '',");
            SQL.AppendLine("@NumeroControl" + InsSql.VarCharTypeForDb(20) + " = '',");
            SQL.AppendLine("@SeHizoLaRetencionIVA" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@NumeroComprobanteRetencion" + InsSql.VarCharTypeForDb(8) + " = '',");
            SQL.AppendLine("@FechaAplicacionRetIVA" + InsSql.DateTypeForDb() + " = '01/01/1900',");
            SQL.AppendLine("@PorcentajeRetencionAplicado" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoRetenido" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@OrigenDeLaRetencion" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@RetencionAplicadaEnPago" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@OrigenInformacionRetencion" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@CxPgeneradaPor" + InsSql.CharTypeForDb(1) + " = '0',");
            SQL.AppendLine("@EsCxPhistorica" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@NumDiasDeVencimiento" + InsSql.NumericTypeForDb(10, 0) + " = 0,");
            SQL.AppendLine("@NumeroDocOrigen" + InsSql.VarCharTypeForDb(15) + " = '',");
            SQL.AppendLine("@CodigoLote" + InsSql.VarCharTypeForDb(10) + " = '',");
            SQL.AppendLine("@GenerarAsientoDeRetiroEnCuenta" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@TotalOtrosImpuestos" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@SeContabilRetIva" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@DondeContabilRetIva" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@CodigoMoneda" + InsSql.VarCharTypeForDb(4) + ",");
            SQL.AppendLine("@EstaAsociadoARendicion" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@ConsecutivoRendicion" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@OrigenDeLaRetencionISLR" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@DondeContabilISLR" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@ISLRAplicadaEnPago" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@MontoRetenidoISLR" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@SeContabilISLR" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@FechaAplicacionImpuestoMunicipal" + InsSql.DateTypeForDb() + " = '01/01/1900',");
            SQL.AppendLine("@NumeroComprobanteImpuestoMunicipal" + InsSql.VarCharTypeForDb(50) + " = '',");
            SQL.AppendLine("@MontoRetenidoImpuestoMunicipal" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@ImpuestoMunicipalRetenido" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@NumeroControlDeFacturaAfectada" + InsSql.VarCharTypeForDb(11) + " = '',");
			SQL.AppendLine("@NumeroDeclaracionAduana" + InsSql.VarCharTypeForDb(20) + " = '',");
            SQL.AppendLine("@FechaDeclaracionAduana" + InsSql.DateTypeForDb() + " = '01/01/1900',");
            SQL.AppendLine("@UsaPrefijoSerie" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@CodigoProveedorOriginalServicio" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@EsUnaCuentaATerceros" + InsSql.VarCharTypeForDb(10) + " = '',");
            SQL.AppendLine("@SeHizoLaDetraccion" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@AplicaIvaAlicuotaEspecial" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@MontoGravableAlicuotaEspecial1" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoIVAAlicuotaEspecial1" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@PorcentajeIvaAlicuotaEspecial1" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoGravableAlicuotaEspecial2" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoIVAAlicuotaEspecial2" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@PorcentajeIvaAlicuotaEspecial2" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@BaseImponibleIGTFML" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@AlicuotaIGTFML" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@MontoIGTFML" + InsSql.DecimalTypeForDb(25, 4) + " = 0,");
            SQL.AppendLine("@NombreOperador" + InsSql.VarCharTypeForDb(10) + " = '',");
            SQL.AppendLine("@FechaUltimaModificacion" + InsSql.DateTypeForDb() + " = '01/01/1900'");
            return SQL.ToString();
        }

        private string SqlSpIns() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("BEGIN");
            SQL.AppendLine("   SET NOCOUNT ON;");
            SQL.AppendLine("   SET DATEFORMAT @DateFormat");
            SQL.AppendLine("   DECLARE @ReturnValue " + InsSql.NumericTypeForDb(10, 0) + "");
            SQL.AppendLine("	IF EXISTS(SELECT ConsecutivoCompania FROM Compania WHERE ConsecutivoCompania = @ConsecutivoCompania)");
            SQL.AppendLine("	BEGIN");
            //SQL.AppendLine("        BEGIN TRAN");
            SQL.AppendLine("            INSERT INTO " + DbSchema + ".CxP(");
            SQL.AppendLine("            ConsecutivoCompania,");
            SQL.AppendLine("            Numero,");
            SQL.AppendLine("            ConsecutivoCxP,");
            SQL.AppendLine("            TipoDeCxP,");
            SQL.AppendLine("            Status,");
            SQL.AppendLine("            CodigoProveedor,");
            SQL.AppendLine("            Fecha,");
            SQL.AppendLine("            FechaCancelacion,");
            SQL.AppendLine("            FechaVencimiento,");
            SQL.AppendLine("            FechaAnulacion,");
            SQL.AppendLine("            Moneda,");
            SQL.AppendLine("            CambioABolivares,");
            SQL.AppendLine("            AplicaParaLibrodeCompras,");
            SQL.AppendLine("            MontoExento,");
            SQL.AppendLine("            MontoGravado,");
            SQL.AppendLine("            MontoIva,");
            SQL.AppendLine("            MontoAbonado,");
            SQL.AppendLine("            DiaDeAplicacion,");
            SQL.AppendLine("            MesDeAplicacion,");
            SQL.AppendLine("            AnoDeAplicacion,");
            SQL.AppendLine("            Observaciones,");
            SQL.AppendLine("            CreditoFiscal,");
            SQL.AppendLine("            TipoDeCompra,");
            SQL.AppendLine("            SeHizoLaRetencion,");
            SQL.AppendLine("            MontoGravableAlicuotaGeneral,");
            SQL.AppendLine("            MontoGravableAlicuota2,");
            SQL.AppendLine("            MontoGravableAlicuota3,");
            SQL.AppendLine("            MontoIVAAlicuotaGeneral,");
            SQL.AppendLine("            MontoIVAAlicuota2,");
            SQL.AppendLine("            MontoIVAAlicuota3,");
            SQL.AppendLine("            NumeroPlanillaDeImportacion,");
            SQL.AppendLine("            NumeroExpedienteDeImportacion,");
            SQL.AppendLine("            TipoDeTransaccion,");
            SQL.AppendLine("            NumeroDeFacturaAfectada,");
            SQL.AppendLine("            NumeroControl,");
            SQL.AppendLine("            SeHizoLaRetencionIVA,");
            SQL.AppendLine("            NumeroComprobanteRetencion,");
            SQL.AppendLine("            FechaAplicacionRetIVA,");
            SQL.AppendLine("            PorcentajeRetencionAplicado,");
            SQL.AppendLine("            MontoRetenido,");
            SQL.AppendLine("            OrigenDeLaRetencion,");
            SQL.AppendLine("            RetencionAplicadaEnPago,");
            SQL.AppendLine("            OrigenInformacionRetencion,");
            SQL.AppendLine("            CxPgeneradaPor,");
            SQL.AppendLine("            EsCxPhistorica,");
            SQL.AppendLine("            NumDiasDeVencimiento,");
            SQL.AppendLine("            NumeroDocOrigen,");
            SQL.AppendLine("            CodigoLote,");
            SQL.AppendLine("            GenerarAsientoDeRetiroEnCuenta,");
            SQL.AppendLine("            TotalOtrosImpuestos,");
            SQL.AppendLine("            SeContabilRetIva,");
            SQL.AppendLine("            DondeContabilRetIva,");
            SQL.AppendLine("            CodigoMoneda,");
            SQL.AppendLine("            EstaAsociadoARendicion,");
            SQL.AppendLine("            ConsecutivoRendicion,");
            SQL.AppendLine("            OrigenDeLaRetencionISLR,");
            SQL.AppendLine("            DondeContabilISLR,");
            SQL.AppendLine("            ISLRAplicadaEnPago,");
            SQL.AppendLine("            MontoRetenidoISLR,");
            SQL.AppendLine("            SeContabilISLR,");
            SQL.AppendLine("            FechaAplicacionImpuestoMunicipal,");
            SQL.AppendLine("            NumeroComprobanteImpuestoMunicipal,");
            SQL.AppendLine("            MontoRetenidoImpuestoMunicipal,");
            SQL.AppendLine("            ImpuestoMunicipalRetenido,");
            SQL.AppendLine("            NumeroControlDeFacturaAfectada,");
			 SQL.AppendLine("            NumeroDeclaracionAduana,");
            SQL.AppendLine("            FechaDeclaracionAduana,");
            SQL.AppendLine("            UsaPrefijoSerie,");
            SQL.AppendLine("            CodigoProveedorOriginalServicio,");
            SQL.AppendLine("            EsUnaCuentaATerceros,");
            SQL.AppendLine("            SeHizoLaDetraccion,");
            SQL.AppendLine("            AplicaIvaAlicuotaEspecial,");
            SQL.AppendLine("            MontoGravableAlicuotaEspecial1,");
            SQL.AppendLine("            MontoIVAAlicuotaEspecial1,");
            SQL.AppendLine("            PorcentajeIvaAlicuotaEspecial1,");
            SQL.AppendLine("            MontoGravableAlicuotaEspecial2,");
            SQL.AppendLine("            MontoIVAAlicuotaEspecial2,");
            SQL.AppendLine("            PorcentajeIvaAlicuotaEspecial2,");
            SQL.AppendLine("            BaseImponibleIGTFML,");
            SQL.AppendLine("            AlicuotaIGTFML,");
            SQL.AppendLine("            MontoIGTFML,");
            SQL.AppendLine("            NombreOperador,");
            SQL.AppendLine("            FechaUltimaModificacion)");          
            SQL.AppendLine("            VALUES(");
            SQL.AppendLine("            @ConsecutivoCompania,");
            SQL.AppendLine("            @Numero,");
            SQL.AppendLine("            @ConsecutivoCxP,");
            SQL.AppendLine("            @TipoDeCxP,");
            SQL.AppendLine("            @Status,");
            SQL.AppendLine("            @CodigoProveedor,");
            SQL.AppendLine("            @Fecha,");
            SQL.AppendLine("            @FechaCancelacion,");
            SQL.AppendLine("            @FechaVencimiento,");
            SQL.AppendLine("            @FechaAnulacion,");
            SQL.AppendLine("            @Moneda,");
            SQL.AppendLine("            @CambioABolivares,");
            SQL.AppendLine("            @AplicaParaLibrodeCompras,");
            SQL.AppendLine("            @MontoExento,");
            SQL.AppendLine("            @MontoGravado,");
            SQL.AppendLine("            @MontoIva,");
            SQL.AppendLine("            @MontoAbonado,");
            SQL.AppendLine("            @DiaDeAplicacion,");
            SQL.AppendLine("            @MesDeAplicacion,");
            SQL.AppendLine("            @AnoDeAplicacion,");
            SQL.AppendLine("            @Observaciones,");
            SQL.AppendLine("            @CreditoFiscal,");
            SQL.AppendLine("            @TipoDeCompra,");
            SQL.AppendLine("            @SeHizoLaRetencion,");
            SQL.AppendLine("            @MontoGravableAlicuotaGeneral,");
            SQL.AppendLine("            @MontoGravableAlicuota2,");
            SQL.AppendLine("            @MontoGravableAlicuota3,");
            SQL.AppendLine("            @MontoIVAAlicuotaGeneral,");
            SQL.AppendLine("            @MontoIVAAlicuota2,");
            SQL.AppendLine("            @MontoIVAAlicuota3,");
            SQL.AppendLine("            @NumeroPlanillaDeImportacion,");
            SQL.AppendLine("            @NumeroExpedienteDeImportacion,");
            SQL.AppendLine("            @TipoDeTransaccion,");
            SQL.AppendLine("            @NumeroDeFacturaAfectada,");
            SQL.AppendLine("            @NumeroControl,");
            SQL.AppendLine("            @SeHizoLaRetencionIVA,");
            SQL.AppendLine("            @NumeroComprobanteRetencion,");
            SQL.AppendLine("            @FechaAplicacionRetIVA,");
            SQL.AppendLine("            @PorcentajeRetencionAplicado,");
            SQL.AppendLine("            @MontoRetenido,");
            SQL.AppendLine("            @OrigenDeLaRetencion,");
            SQL.AppendLine("            @RetencionAplicadaEnPago,");
            SQL.AppendLine("            @OrigenInformacionRetencion,");
            SQL.AppendLine("            @CxPgeneradaPor,");
            SQL.AppendLine("            @EsCxPhistorica,");
            SQL.AppendLine("            @NumDiasDeVencimiento,");
            SQL.AppendLine("            @NumeroDocOrigen,");
            SQL.AppendLine("            @CodigoLote,");
            SQL.AppendLine("            @GenerarAsientoDeRetiroEnCuenta,");
            SQL.AppendLine("            @TotalOtrosImpuestos,");
            SQL.AppendLine("            @SeContabilRetIva,");
            SQL.AppendLine("            @DondeContabilRetIva,");
            SQL.AppendLine("            @CodigoMoneda,");
            SQL.AppendLine("            @EstaAsociadoARendicion,");
            SQL.AppendLine("            @ConsecutivoRendicion,");
            SQL.AppendLine("            @OrigenDeLaRetencionISLR,");
            SQL.AppendLine("            @DondeContabilISLR,");
            SQL.AppendLine("            @ISLRAplicadaEnPago,");
            SQL.AppendLine("            @MontoRetenidoISLR,");
            SQL.AppendLine("            @SeContabilISLR,");
            SQL.AppendLine("            @FechaAplicacionImpuestoMunicipal,");
            SQL.AppendLine("            @NumeroComprobanteImpuestoMunicipal,");
            SQL.AppendLine("            @MontoRetenidoImpuestoMunicipal,");
            SQL.AppendLine("            @ImpuestoMunicipalRetenido,");
            SQL.AppendLine("            @NumeroControlDeFacturaAfectada,");
			SQL.AppendLine("            @NumeroDeclaracionAduana,");
            SQL.AppendLine("            @FechaDeclaracionAduana,");
            SQL.AppendLine("            @UsaPrefijoSerie,");
            SQL.AppendLine("            @CodigoProveedorOriginalServicio,");
            SQL.AppendLine("            @EsUnaCuentaATerceros,");
            SQL.AppendLine("            @SeHizoLaDetraccion,");
            SQL.AppendLine("            @AplicaIvaAlicuotaEspecial,");
            SQL.AppendLine("            @MontoGravableAlicuotaEspecial1,");
            SQL.AppendLine("            @MontoIVAAlicuotaEspecial1,");
            SQL.AppendLine("            @PorcentajeIvaAlicuotaEspecial1,");
            SQL.AppendLine("            @MontoGravableAlicuotaEspecial2,");
            SQL.AppendLine("            @MontoIVAAlicuotaEspecial2,");
            SQL.AppendLine("            @PorcentajeIvaAlicuotaEspecial2,");
            SQL.AppendLine("            @BaseImponibleIGTFML,");
            SQL.AppendLine("            @AlicuotaIGTFML,");
            SQL.AppendLine("            @MontoIGTFML,");
            SQL.AppendLine("            @NombreOperador,");
            SQL.AppendLine("            @FechaUltimaModificacion)");
            SQL.AppendLine("            SET @ReturnValue = @@ROWCOUNT");
            //SQL.AppendLine("        COMMIT TRAN");
            SQL.AppendLine("        RETURN @ReturnValue ");
            SQL.AppendLine("	END");
            SQL.AppendLine("	ELSE");
            SQL.AppendLine("		RETURN -1");
            SQL.AppendLine("END");
            return SQL.ToString();
        }

        private string SqlSpUpdParameters() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("@DateFormat" + InsSql.VarCharTypeForDb(3) + ",");
            SQL.AppendLine("@ConsecutivoCompania" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@Numero" + InsSql.VarCharTypeForDb(20) + ",");
            SQL.AppendLine("@ConsecutivoCxP" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@TipoDeCxP" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@Status" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@CodigoProveedor" + InsSql.VarCharTypeForDb(10) + ",");
            SQL.AppendLine("@Fecha" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@FechaCancelacion" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@FechaVencimiento" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@FechaAnulacion" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@CodigoMoneda" + InsSql.VarCharTypeForDb(4) + ",");
            SQL.AppendLine("@Moneda" + InsSql.VarCharTypeForDb(10) + ",");
            SQL.AppendLine("@CambioABolivares" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@AplicaParaLibrodeCompras" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@MontoExento" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoGravado" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoIva" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoAbonado" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MesDeAplicacion" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@AnoDeAplicacion" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@Observaciones" + InsSql.VarCharTypeForDb(255) + ",");
            SQL.AppendLine("@CreditoFiscal" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@TipoDeCompra" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@SeHizoLaRetencion" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@MontoGravableAlicuotaGeneral" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoGravableAlicuota2" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoGravableAlicuota3" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoIVAAlicuotaGeneral" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoIVAAlicuota2" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoIVAAlicuota3" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@NumeroPlanillaDeImportacion" + InsSql.VarCharTypeForDb(20) + ",");
            SQL.AppendLine("@NumeroExpedienteDeImportacion" + InsSql.VarCharTypeForDb(20) + ",");
            SQL.AppendLine("@TipoDeTransaccion" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@NumeroDeFacturaAfectada" + InsSql.VarCharTypeForDb(11) + ",");
            SQL.AppendLine("@NumeroControl" + InsSql.VarCharTypeForDb(20) + ",");
            SQL.AppendLine("@SeHizoLaRetencionIVA" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@NumeroComprobanteRetencion" + InsSql.VarCharTypeForDb(8) + ",");
            SQL.AppendLine("@FechaAplicacionRetIVA" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@PorcentajeRetencionAplicado" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoRetenido" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@OrigenDeLaRetencion" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@RetencionAplicadaEnPago" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@OrigenInformacionRetencion" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@CxPgeneradaPor" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@EsCxPhistorica" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@NumDiasDeVencimiento" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@NumeroDocOrigen" + InsSql.VarCharTypeForDb(15) + ",");
            SQL.AppendLine("@CodigoLote" + InsSql.VarCharTypeForDb(10) + ",");
            SQL.AppendLine("@GenerarAsientoDeRetiroEnCuenta" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@TotalOtrosImpuestos" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@SeContabilRetIva" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@DondeContabilRetIva" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@OrigenDeLaRetencionISLR" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@DondeContabilISLR" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@ISLRAplicadaEnPago" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@MontoRetenidoISLR" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@SeContabilISLR" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@FechaAplicacionImpuestoMunicipal" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@NumeroComprobanteImpuestoMunicipal" + InsSql.VarCharTypeForDb(50) + ",");
            SQL.AppendLine("@MontoRetenidoImpuestoMunicipal" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@ImpuestoMunicipalRetenido" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@NumeroControlDeFacturaAfectada" + InsSql.VarCharTypeForDb(11) + ",");
            SQL.AppendLine("@ConsecutivoRendicion" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@EstaAsociadoARendicion" + InsSql.CharTypeForDb(1) + ",");
			SQL.AppendLine("@NumeroDeclaracionAduana" + InsSql.VarCharTypeForDb(20) + ",");
            SQL.AppendLine("@FechaDeclaracionAduana" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@UsaPrefijoSerie" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@CodigoProveedorOriginalServicio" + InsSql.CharTypeForDb(1) + " = 'N',");
            SQL.AppendLine("@EsUnaCuentaATerceros" + InsSql.VarCharTypeForDb(10) + " = '',");
            SQL.AppendLine("@SeHizoLaDetraccion" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@AplicaIvaAlicuotaEspecial" + InsSql.CharTypeForDb(1) + ",");
            SQL.AppendLine("@MontoGravableAlicuotaEspecial1" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoIVAAlicuotaEspecial1" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@PorcentajeIvaAlicuotaEspecial1" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoGravableAlicuotaEspecial2" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoIVAAlicuotaEspecial2" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@PorcentajeIvaAlicuotaEspecial2" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@BaseImponibleIGTFML" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@AlicuotaIGTFML" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@MontoIGTFML" + InsSql.DecimalTypeForDb(25, 4) + ",");
            SQL.AppendLine("@NombreOperador" + InsSql.VarCharTypeForDb(10) + ",");
            SQL.AppendLine("@FechaUltimaModificacion" + InsSql.DateTypeForDb() + ",");
            SQL.AppendLine("@TimeStampAsInt" + InsSql.BigintTypeForDb());
            return SQL.ToString();
        }

        private string SqlSpUpd() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("BEGIN");
            SQL.AppendLine("   SET NOCOUNT ON;");
            SQL.AppendLine("   SET DATEFORMAT @DateFormat");
            SQL.AppendLine("   DECLARE @CurrentTimeStamp timestamp");
            SQL.AppendLine("   DECLARE @ValidationMsg " + InsSql.VarCharTypeForDb(1500) + " --No puede ser más");
            SQL.AppendLine("   DECLARE @ReturnValue " + InsSql.NumericTypeForDb(10, 0) + "");
            //SQL.AppendLine("--DECLARE @CanBeChanged bit");
            SQL.AppendLine("   SET @ReturnValue = -1");
            SQL.AppendLine("   SET @ValidationMsg = ''");
            SQL.AppendLine("   IF EXISTS(SELECT ConsecutivoCompania FROM " + DbSchema + ".CxP WHERE ConsecutivoCompania = @ConsecutivoCompania AND ConsecutivoCxP = @ConsecutivoCxP)");
            SQL.AppendLine("   BEGIN");
            SQL.AppendLine("      SELECT @CurrentTimeStamp = fldTimeStamp FROM " + DbSchema + ".CxP WHERE ConsecutivoCompania = @ConsecutivoCompania AND ConsecutivoCxP = @ConsecutivoCxP");
            SQL.AppendLine("      IF (CAST(@CurrentTimeStamp AS bigint) = @TimeStampAsInt)");
            SQL.AppendLine("      BEGIN");
            SQL.AppendLine("--Para Validaciones de FK Lógicas crear e invocar:DECLARE @CanBeChanged bit; EXEC @CanBeChanged = " + DbSchema + ".Gp_CxPCanBeUpdated @ConsecutivoCompania,@ConsecutivoCxP, @CurrentTimeStamp, @ValidationMsg out");
            //SQL.AppendLine("--IF @CanBeChanged = 1 --True");
            //SQL.AppendLine("--BEGIN");
            SQL.AppendLine("         BEGIN TRAN");
            SQL.AppendLine("         UPDATE " + DbSchema + ".CxP");
            SQL.AppendLine("            SET Numero = @Numero,");
            SQL.AppendLine("               TipoDeCxP = @TipoDeCxP,");
            SQL.AppendLine("               Status = @Status,");
            SQL.AppendLine("               CodigoProveedor = @CodigoProveedor,");
            SQL.AppendLine("               Fecha = @Fecha,");
            SQL.AppendLine("               FechaCancelacion = @FechaCancelacion,");
            SQL.AppendLine("               FechaVencimiento = @FechaVencimiento,");
            SQL.AppendLine("               FechaAnulacion = @FechaAnulacion,");
            SQL.AppendLine("               CodigoMoneda = @CodigoMoneda,");
            SQL.AppendLine("               Moneda = @Moneda,");
            SQL.AppendLine("               CambioABolivares = @CambioABolivares,");
            SQL.AppendLine("               AplicaParaLibrodeCompras = @AplicaParaLibrodeCompras,");
            SQL.AppendLine("               MontoExento = @MontoExento,");
            SQL.AppendLine("               MontoGravado = @MontoGravado,");
            SQL.AppendLine("               MontoIva = @MontoIva,");
            SQL.AppendLine("               MontoAbonado = @MontoAbonado,");
            SQL.AppendLine("               DiaDeAplicacion = Day(@FechaCancelacion),");
            SQL.AppendLine("               MesDeAplicacion = @MesDeAplicacion,");
            SQL.AppendLine("               AnoDeAplicacion = @AnoDeAplicacion,");
            SQL.AppendLine("               Observaciones = @Observaciones,");
            SQL.AppendLine("               CreditoFiscal = @CreditoFiscal,");
            SQL.AppendLine("               TipoDeCompra = @TipoDeCompra,");
            SQL.AppendLine("               SeHizoLaRetencion = @SeHizoLaRetencion,");
            SQL.AppendLine("               MontoGravableAlicuotaGeneral = @MontoGravableAlicuotaGeneral,");
            SQL.AppendLine("               MontoGravableAlicuota2 = @MontoGravableAlicuota2,");
            SQL.AppendLine("               MontoGravableAlicuota3 = @MontoGravableAlicuota3,");
            SQL.AppendLine("               MontoIVAAlicuotaGeneral = @MontoIVAAlicuotaGeneral,");
            SQL.AppendLine("               MontoIVAAlicuota2 = @MontoIVAAlicuota2,");
            SQL.AppendLine("               MontoIVAAlicuota3 = @MontoIVAAlicuota3,");
            SQL.AppendLine("               NumeroPlanillaDeImportacion = @NumeroPlanillaDeImportacion,");
            SQL.AppendLine("               NumeroExpedienteDeImportacion = @NumeroExpedienteDeImportacion,");
            SQL.AppendLine("               TipoDeTransaccion = @TipoDeTransaccion,");
            SQL.AppendLine("               NumeroDeFacturaAfectada = @NumeroDeFacturaAfectada,");
            SQL.AppendLine("               NumeroControl = @NumeroControl,");
            SQL.AppendLine("               SeHizoLaRetencionIVA = @SeHizoLaRetencionIVA,");
            SQL.AppendLine("               NumeroComprobanteRetencion = @NumeroComprobanteRetencion,");
            SQL.AppendLine("               FechaAplicacionRetIVA = @FechaAplicacionRetIVA,");
            SQL.AppendLine("               PorcentajeRetencionAplicado = @PorcentajeRetencionAplicado,");
            SQL.AppendLine("               MontoRetenido = @MontoRetenido,");
            SQL.AppendLine("               OrigenDeLaRetencion = @OrigenDeLaRetencion,");
            SQL.AppendLine("               RetencionAplicadaEnPago = @RetencionAplicadaEnPago,");
            SQL.AppendLine("               OrigenInformacionRetencion = @OrigenInformacionRetencion,");
            SQL.AppendLine("               CxPgeneradaPor = @CxPgeneradaPor,");
            SQL.AppendLine("               EsCxPhistorica = @EsCxPhistorica,");
            SQL.AppendLine("               NumDiasDeVencimiento = @NumDiasDeVencimiento,");
            SQL.AppendLine("               NumeroDocOrigen = @NumeroDocOrigen,");
            SQL.AppendLine("               CodigoLote = @CodigoLote,");
            SQL.AppendLine("               GenerarAsientoDeRetiroEnCuenta = @GenerarAsientoDeRetiroEnCuenta,");
            SQL.AppendLine("               TotalOtrosImpuestos = @TotalOtrosImpuestos,");
            SQL.AppendLine("               SeContabilRetIva = @SeContabilRetIva,");
            SQL.AppendLine("               DondeContabilRetIva = @DondeContabilRetIva,");
            SQL.AppendLine("               OrigenDeLaRetencionISLR = @OrigenDeLaRetencionISLR,");
            SQL.AppendLine("               DondeContabilISLR = @DondeContabilISLR,");
            SQL.AppendLine("               ISLRAplicadaEnPago = @ISLRAplicadaEnPago,");
            SQL.AppendLine("               MontoRetenidoISLR = @MontoRetenidoISLR,");
            SQL.AppendLine("               SeContabilISLR = @SeContabilISLR,");
            SQL.AppendLine("               FechaAplicacionImpuestoMunicipal = @FechaAplicacionImpuestoMunicipal,");
            SQL.AppendLine("               NumeroComprobanteImpuestoMunicipal = @NumeroComprobanteImpuestoMunicipal,");
            SQL.AppendLine("               MontoRetenidoImpuestoMunicipal = @MontoRetenidoImpuestoMunicipal,");
            SQL.AppendLine("               ImpuestoMunicipalRetenido = @ImpuestoMunicipalRetenido,");
            SQL.AppendLine("               NumeroControlDeFacturaAfectada = @NumeroControlDeFacturaAfectada,");
            SQL.AppendLine("               ConsecutivoRendicion = @ConsecutivoRendicion,");
            SQL.AppendLine("               EstaAsociadoARendicion = @EstaAsociadoARendicion,");
	        SQL.AppendLine("               NumeroDeclaracionAduana = @NumeroDeclaracionAduana,");
            SQL.AppendLine("               FechaDeclaracionAduana = @FechaDeclaracionAduana,");
            SQL.AppendLine("               UsaPrefijoSerie = @UsaPrefijoSerie,");
            SQL.AppendLine("               CodigoProveedorOriginalServicio = @CodigoProveedorOriginalServicio,");
            SQL.AppendLine("               EsUnaCuentaATerceros = @EsUnaCuentaATerceros,");
            SQL.AppendLine("               SeHizoLaDetraccion = @SeHizoLaDetraccion,");
            SQL.AppendLine("               AplicaIvaAlicuotaEspecial = @AplicaIvaAlicuotaEspecial,");
            SQL.AppendLine("               MontoGravableAlicuotaEspecial1 = @MontoGravableAlicuotaEspecial1,");
            SQL.AppendLine("               MontoIVAAlicuotaEspecial1 = @MontoIVAAlicuotaEspecial1,");
            SQL.AppendLine("               PorcentajeIvaAlicuotaEspecial1 = @PorcentajeIvaAlicuotaEspecial1,");
            SQL.AppendLine("               MontoGravableAlicuotaEspecial2 = @MontoGravableAlicuotaEspecial2,");
            SQL.AppendLine("               MontoIVAAlicuotaEspecial2 = @MontoIVAAlicuotaEspecial2,");
            SQL.AppendLine("               PorcentajeIvaAlicuotaEspecial2 = @PorcentajeIvaAlicuotaEspecial2,");
            SQL.AppendLine("               BaseImponibleIGTFML = @BaseImponibleIGTFML,");
            SQL.AppendLine("               AlicuotaIGTFML = @AlicuotaIGTFML,");
            SQL.AppendLine("               MontoIGTFML = @MontoIGTFML,");
            SQL.AppendLine("               NombreOperador = @NombreOperador,");
            SQL.AppendLine("               FechaUltimaModificacion = @FechaUltimaModificacion");
            SQL.AppendLine("            WHERE fldTimeStamp = @CurrentTimeStamp");
            SQL.AppendLine("               AND ConsecutivoCompania = @ConsecutivoCompania");
            SQL.AppendLine("               AND ConsecutivoCxP = @ConsecutivoCxP");
            SQL.AppendLine("         SET @ReturnValue = @@ROWCOUNT");
            SQL.AppendLine("         IF @@ERROR = 0");
            SQL.AppendLine("         BEGIN");
            SQL.AppendLine("            COMMIT TRAN");
            SQL.AppendLine("            IF @ReturnValue = 0");
            SQL.AppendLine("               RAISERROR('El registro ha sido modificado o eliminado por otro usuario', 14, 1)");
            SQL.AppendLine("         END");
            SQL.AppendLine("         ELSE");
            SQL.AppendLine("         BEGIN");
            SQL.AppendLine("            SET @ReturnValue = -1");
            SQL.AppendLine("            SET @ValidationMsg = 'Se ha producido un error al Modificar: ' + CAST(@@ERROR AS NVARCHAR(8))");
            SQL.AppendLine("            RAISERROR(@ValidationMsg, 14 ,1)");
            SQL.AppendLine("            ROLLBACK");
            SQL.AppendLine("         END");
            //SQL.AppendLine("--END");
            //SQL.AppendLine("--ELSE");
            //SQL.AppendLine("--	RAISERROR('El registro no puede ser modificado: %s', 14, 1, @ValidationMsg)");
            SQL.AppendLine("      END");
            SQL.AppendLine("      ELSE");
            SQL.AppendLine("         RAISERROR('El registro ha sido modificado o eliminado por otro usuario.', 14, 1)");
            SQL.AppendLine("   END");
            SQL.AppendLine("   ELSE");
            SQL.AppendLine("      RAISERROR('El registro no existe.', 14, 1)");
            SQL.AppendLine("   RETURN @ReturnValue");
            SQL.AppendLine("END");
            return SQL.ToString();
        }

        private string SqlSpDelParameters() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("@ConsecutivoCompania" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@ConsecutivoCxP" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@TimeStampAsInt" + InsSql.BigintTypeForDb());
            return SQL.ToString();
        }

        private string SqlSpDel() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("BEGIN");
            SQL.AppendLine("   SET NOCOUNT ON;");
            SQL.AppendLine("   DECLARE @CurrentTimeStamp timestamp");
            SQL.AppendLine("   DECLARE @ValidationMsg " + InsSql.VarCharTypeForDb(1500) + " --No puede ser más");
            SQL.AppendLine("   DECLARE @ReturnValue " + InsSql.NumericTypeForDb(10, 0) + "");
            //SQL.AppendLine("--DECLARE @CanBeDeleted bit");
            SQL.AppendLine("   SET @ReturnValue = -1");
            SQL.AppendLine("   SET @ValidationMsg = ''");
            SQL.AppendLine("   IF EXISTS(SELECT ConsecutivoCompania FROM " + DbSchema + ".CxP WHERE ConsecutivoCompania = @ConsecutivoCompania AND ConsecutivoCxP = @ConsecutivoCxP)");
            SQL.AppendLine("   BEGIN");
            SQL.AppendLine("      SELECT @CurrentTimeStamp = fldTimeStamp FROM " + DbSchema + ".CxP WHERE ConsecutivoCompania = @ConsecutivoCompania AND ConsecutivoCxP = @ConsecutivoCxP");
            SQL.AppendLine("      IF (CAST(@CurrentTimeStamp AS bigint) = @TimeStampAsInt)");
            SQL.AppendLine("      BEGIN");
            SQL.AppendLine("--Para Validaciones de FK Lógicas crear e invocar:DECLARE @CanBeDeleted bit; EXEC @CanBeDeleted = " + DbSchema + ".Gp_CxPCanBeDeleted @ConsecutivoCompania,@ConsecutivoCxP, @CurrentTimeStamp, @ValidationMsg out");
            //SQL.AppendLine("--IF @CanBeDeleted = 1 --True");
            //SQL.AppendLine("--BEGIN");
            SQL.AppendLine("         BEGIN TRAN");
            SQL.AppendLine("         DELETE FROM " + DbSchema + ".CxP");
            SQL.AppendLine("            WHERE fldTimeStamp = @CurrentTimeStamp");
            SQL.AppendLine("               AND ConsecutivoCompania = @ConsecutivoCompania");
            SQL.AppendLine("               AND ConsecutivoCxP = @ConsecutivoCxP");
            SQL.AppendLine("         SET @ReturnValue = @@ROWCOUNT");
            SQL.AppendLine("         IF @@ERROR = 0");
            SQL.AppendLine("         BEGIN");
            SQL.AppendLine("            COMMIT TRAN");
            SQL.AppendLine("            IF @ReturnValue = 0");
            SQL.AppendLine("               RAISERROR('El registro ha sido modificado o eliminado por otro usuario', 14, 1)");
            SQL.AppendLine("         END");
            SQL.AppendLine("         ELSE");
            SQL.AppendLine("         BEGIN");
            SQL.AppendLine("            SET @ReturnValue = -1");
            SQL.AppendLine("            SET @ValidationMsg = 'Se ha producido un error al Eliminar: ' + CAST(@@ERROR AS NVARCHAR(8))");
            SQL.AppendLine("            RAISERROR(@ValidationMsg, 14 ,1)");
            SQL.AppendLine("            ROLLBACK");
            SQL.AppendLine("         END");
            //SQL.AppendLine("--END");
            //SQL.AppendLine("--ELSE");
            //SQL.AppendLine("--	RAISERROR('El registro no puede ser eliminado: %s', 14, 1, @ValidationMsg)");
            SQL.AppendLine("      END");
            SQL.AppendLine("      ELSE");
            SQL.AppendLine("         RAISERROR('El registro ha sido modificado o eliminado por otro usuario.', 14, 1)");
            SQL.AppendLine("   END");
            SQL.AppendLine("   ELSE");
            SQL.AppendLine("      RAISERROR('El registro no existe.', 14, 1)");
            SQL.AppendLine("   RETURN @ReturnValue");
            SQL.AppendLine("END");
            return SQL.ToString();
        }

        private string SqlSpGetParameters() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("@ConsecutivoCompania" + InsSql.NumericTypeForDb(10, 0) + ",");
            SQL.AppendLine("@ConsecutivoCxP" + InsSql.NumericTypeForDb(10, 0));
            return SQL.ToString();
        }

        private string SqlSpGet() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("BEGIN");
            SQL.AppendLine("   SET NOCOUNT ON;");
            SQL.AppendLine("   SELECT ");
            SQL.AppendLine("         CxP.ConsecutivoCompania,");
            SQL.AppendLine("         CxP.Numero,");
            SQL.AppendLine("         CxP.ConsecutivoCxP,");
            SQL.AppendLine("         CxP.TipoDeCxP,");
            SQL.AppendLine("         CxP.Status,");
            SQL.AppendLine("         CxP.CodigoProveedor,");
            SQL.AppendLine("         Adm.Gv_Proveedor_B1.nombreProveedor AS NombreProveedor,");
            SQL.AppendLine("         CxP.Fecha,");
            SQL.AppendLine("         CxP.FechaCancelacion,");
            SQL.AppendLine("         CxP.FechaVencimiento,");
            SQL.AppendLine("         CxP.FechaAnulacion,");
            SQL.AppendLine("         CxP.CodigoMoneda,");
            SQL.AppendLine("         CxP.Moneda,");
            SQL.AppendLine("         CxP.CambioABolivares,");
            SQL.AppendLine("         CxP.AplicaParaLibrodeCompras,");
            SQL.AppendLine("         CxP.MontoExento,");
            SQL.AppendLine("         CxP.MontoGravado,");
            SQL.AppendLine("         CxP.MontoIva,");
            SQL.AppendLine("         CxP.MontoAbonado,");
            SQL.AppendLine("         CxP.MesDeAplicacion,");
            SQL.AppendLine("         CxP.AnoDeAplicacion,");
            SQL.AppendLine("         CxP.Observaciones,");
            SQL.AppendLine("         CxP.CreditoFiscal,");
            SQL.AppendLine("         CxP.TipoDeCompra,");
            SQL.AppendLine("         CxP.SeHizoLaRetencion,");
            SQL.AppendLine("         CxP.MontoGravableAlicuotaGeneral,");
            SQL.AppendLine("         CxP.MontoGravableAlicuota2,");
            SQL.AppendLine("         CxP.MontoGravableAlicuota3,");
            SQL.AppendLine("         CxP.MontoIVAAlicuotaGeneral,");
            SQL.AppendLine("         CxP.MontoIVAAlicuota2,");
            SQL.AppendLine("         CxP.MontoIVAAlicuota3,");
            SQL.AppendLine("         CxP.NumeroPlanillaDeImportacion,");
            SQL.AppendLine("         CxP.NumeroExpedienteDeImportacion,");
            SQL.AppendLine("         CxP.TipoDeTransaccion,");
            SQL.AppendLine("         CxP.NumeroDeFacturaAfectada,");
            SQL.AppendLine("         CxP.NumeroControl,");
            SQL.AppendLine("         CxP.SeHizoLaRetencionIVA,");
            SQL.AppendLine("         CxP.NumeroComprobanteRetencion,");
            SQL.AppendLine("         CxP.FechaAplicacionRetIVA,");
            SQL.AppendLine("         CxP.PorcentajeRetencionAplicado,");
            SQL.AppendLine("         CxP.MontoRetenido,");
            SQL.AppendLine("         CxP.OrigenDeLaRetencion,");
            SQL.AppendLine("         CxP.RetencionAplicadaEnPago,");
            SQL.AppendLine("         CxP.OrigenInformacionRetencion,");
            SQL.AppendLine("         CxP.CxPgeneradaPor,");
            SQL.AppendLine("         CxP.EsCxPhistorica,");
            SQL.AppendLine("         CxP.NumDiasDeVencimiento,");
            SQL.AppendLine("         CxP.NumeroDocOrigen,");
            SQL.AppendLine("         CxP.CodigoLote,");
            SQL.AppendLine("         CxP.GenerarAsientoDeRetiroEnCuenta,");
            SQL.AppendLine("         CxP.TotalOtrosImpuestos,");
            SQL.AppendLine("         CxP.SeContabilRetIva,");
            SQL.AppendLine("         CxP.DondeContabilRetIva,");
            SQL.AppendLine("         CxP.OrigenDeLaRetencionISLR,");
            SQL.AppendLine("         CxP.DondeContabilISLR,");
            SQL.AppendLine("         CxP.ISLRAplicadaEnPago,");
            SQL.AppendLine("         CxP.MontoRetenidoISLR,");
            SQL.AppendLine("         CxP.SeContabilISLR,");
            SQL.AppendLine("         CxP.FechaAplicacionImpuestoMunicipal,");
            SQL.AppendLine("         CxP.NumeroComprobanteImpuestoMunicipal,");
            SQL.AppendLine("         CxP.MontoRetenidoImpuestoMunicipal,");
            SQL.AppendLine("         CxP.ImpuestoMunicipalRetenido,");
            SQL.AppendLine("         CxP.NumeroControlDeFacturaAfectada,");
            SQL.AppendLine("         CxP.ConsecutivoRendicion,");
            SQL.AppendLine("         CxP.EstaAsociadoARendicion,");
		    SQL.AppendLine("         CxP.NumeroDeclaracionAduana,");
            SQL.AppendLine("         CxP.FechaDeclaracionAduana,");
            SQL.AppendLine("         CxP.UsaPrefijoSerie,");
            SQL.AppendLine("         CxP.CodigoProveedorOriginalServicio,");
            SQL.AppendLine("         CxP.EsUnaCuentaATerceros,");
            SQL.AppendLine("         CxP.SeHizoLaDetraccion,");
            SQL.AppendLine("         CxP.AplicaIvaAlicuotaEspecial,");
            SQL.AppendLine("         CxP.MontoGravableAlicuotaEspecial1,");
            SQL.AppendLine("         CxP.MontoIVAAlicuotaEspecial1,");
            SQL.AppendLine("         CxP.PorcentajeIvaAlicuotaEspecial1,");
            SQL.AppendLine("         CxP.MontoGravableAlicuotaEspecial2,");
            SQL.AppendLine("         CxP.MontoIVAAlicuotaEspecial2,");
            SQL.AppendLine("         CxP.PorcentajeIvaAlicuotaEspecial2,");
            SQL.AppendLine("         CxP.BaseImponibleIGTFML,");
            SQL.AppendLine("         CxP.AlicuotaIGTFML,");
            SQL.AppendLine("         CxP.MontoIGTFML,");
            SQL.AppendLine("         CxP.NombreOperador,");
            SQL.AppendLine("         CxP.FechaUltimaModificacion,");
            SQL.AppendLine("         CAST(CxP.fldTimeStamp AS bigint) AS fldTimeStampBigint,");
            SQL.AppendLine("         CxP.fldTimeStamp");
            SQL.AppendLine("      FROM " + DbSchema + ".CxP");
            SQL.AppendLine("             INNER JOIN Adm.Gv_Proveedor_B1 ON " + DbSchema + ".CxP.CodigoProveedor = Adm.Gv_Proveedor_B1.codigoProveedor");
            SQL.AppendLine("             INNER JOIN dbo.Moneda ON " + DbSchema + ".CxP.CodigoMoneda = dbo.Moneda.Codigo");
            SQL.AppendLine("             INNER JOIN Adm.Gv_Rendicion_B1 ON " + DbSchema + ".CxP.ConsecutivoRendicion = Adm.Gv_Rendicion_B1.Consecutivo");
            SQL.AppendLine("      WHERE CxP.ConsecutivoCompania = @ConsecutivoCompania");
            SQL.AppendLine("         AND CxP.ConsecutivoCxP = @ConsecutivoCxP");
            SQL.AppendLine("   RETURN @@ROWCOUNT");
            SQL.AppendLine("END");
            return SQL.ToString();
        }

        private string SqlSpSearchParameters() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("@SQLWhere" + InsSql.VarCharTypeForDb(2000) + " = null,");
            SQL.AppendLine("@SQLOrderBy" + InsSql.VarCharTypeForDb(500) + " = null,");
            SQL.AppendLine("@DateFormat" + InsSql.VarCharTypeForDb(3) + " = null,");
            SQL.AppendLine("@UseTopClausule" + InsSql.VarCharTypeForDb(1) + " = 'S'");
            return SQL.ToString();
        }

        private string SqlSpSearch() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("BEGIN");
            SQL.AppendLine("   SET NOCOUNT ON;");
            SQL.AppendLine("   DECLARE @strSQL AS " + InsSql.VarCharTypeForDb(7000));
            SQL.AppendLine("   DECLARE @TopClausule AS " + InsSql.VarCharTypeForDb(10));
            SQL.AppendLine("   IF(@UseTopClausule = 'S') ");
            SQL.AppendLine("    SET @TopClausule = 'TOP 500'");
            SQL.AppendLine("   ELSE ");
            SQL.AppendLine("    SET @TopClausule = ''");
            SQL.AppendLine("   SET @strSQL = ");
            SQL.AppendLine("    ' SET DateFormat ' + @DateFormat + ");
            SQL.AppendLine("    ' SELECT ' + @TopClausule + '");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.Numero,");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.StatusStr,");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.CodigoProveedor,");
            SQL.AppendLine("      Adm.Gv_Proveedor_B1.nombreProveedor AS NombreProveedor,");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.Fecha,");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.FechaAplicacionImpuestoMunicipal,");
            SQL.AppendLine("      ''COLPIVOTE'' AS ColControl,");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.ConsecutivoCompania,");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.ConsecutivoCxP,");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.TipoDeCxP,");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.Status,");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.FechaCancelacion,");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.Observaciones,");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.ConsecutivoRendicion,");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.CxPgeneradaPor,");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.BaseImponibleIGTFML,");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.AlicuotaIGTFML,");
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.MontoIGTFML,");			
            SQL.AppendLine("      " + DbSchema + ".Gv_CxP_B1.fldTimeStampBigint");
            SQL.AppendLine("      FROM " + DbSchema + ".Gv_CxP_B1");
            SQL.AppendLine("      INNER JOIN Adm.Gv_Proveedor_B1 ON  " + DbSchema + ".Gv_CxP_B1.CodigoProveedor = Adm.Gv_Proveedor_B1.codigoProveedor");
            SQL.AppendLine("      AND " + DbSchema + ".Gv_CxP_B1.ConsecutivoCompania = Adm.Gv_Proveedor_B1.ConsecutivoCompania");
            SQL.AppendLine("      INNER JOIN dbo.Moneda ON  " + DbSchema + ".Gv_CxP_B1.CodigoMoneda = dbo.Moneda.Codigo");
            //SQL.AppendLine("      INNER JOIN Adm.Gv_Rendicion_B1 ON  " + DbSchema + ".Gv_CxP_B1.ConsecutivoRendicion = Adm.Gv_Rendicion_B1.Consecutivo");
            //SQL.AppendLine("      AND " + DbSchema + ".Gv_CxP_B1.ConsecutivoCompania = Adm.Gv_Rendicion_B1.ConsecutivoCompania");
            SQL.AppendLine("'   IF (NOT @SQLWhere IS NULL) AND (@SQLWhere <> '')");
            SQL.AppendLine("      SET @strSQL = @strSQL + ' WHERE ' + @SQLWhere");
            SQL.AppendLine("   IF (NOT @SQLOrderBy IS NULL) AND (@SQLOrderBy <> '')");
            SQL.AppendLine("      SET @strSQL = @strSQL + ' ORDER BY ' + @SQLOrderBy");
            SQL.AppendLine("   EXEC(@strSQL)");
            SQL.AppendLine("END");
            return SQL.ToString();
        }

        private string SqlSpGetFKParameters() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("@ConsecutivoCompania" + InsSql.NumericTypeForDb(10, 0));
            return SQL.ToString();
        }

        private string SqlSpGetFK() {
            StringBuilder SQL = new StringBuilder();
            SQL.AppendLine("BEGIN");
            SQL.AppendLine("   SET NOCOUNT ON;");
            SQL.AppendLine("   SELECT ");
            SQL.AppendLine("      " + DbSchema + ".CxP.ConsecutivoCompania,");
            SQL.AppendLine("      " + DbSchema + ".CxP.Numero,");
            SQL.AppendLine("      " + DbSchema + ".CxP.ConsecutivoCxP,");
            SQL.AppendLine("      " + DbSchema + ".CxP.TipoDeCxP,");
            SQL.AppendLine("      " + DbSchema + ".CxP.Status,");
            SQL.AppendLine("      " + DbSchema + ".CxP.CodigoProveedor,");
            SQL.AppendLine("      " + DbSchema + ".CxP.FechaCancelacion,");
            SQL.AppendLine("      " + DbSchema + ".CxP.CodigoMoneda,");
            SQL.AppendLine("      " + DbSchema + ".CxP.Moneda,");
            SQL.AppendLine("      " + DbSchema + ".CxP.Observaciones,");
            SQL.AppendLine("      " + DbSchema + ".CxP.FechaAplicacionImpuestoMunicipal,");
            SQL.AppendLine("      " + DbSchema + ".CxP.ConsecutivoRendicion");
            SQL.AppendLine("      FROM " + DbSchema + ".CxP");
            SQL.AppendLine("   RETURN @@ROWCOUNT");
            SQL.AppendLine("END");
            return SQL.ToString();
        }
        #endregion //Queries

        bool CrearTabla() {
            bool vResult = insDbo.Create(DbSchema + ".CxP", SqlCreateTable(), false, eDboType.Tabla);
            return vResult;
        }

        bool CrearVistas(){
            bool vResult = false;
            LibViews insVistas = new LibViews();
            vResult = insVistas.Create(DbSchema + ".Gv_EnumTipoDeCxC", LibTpvCreator.SqlViewStandardEnum(typeof(eTipoDeCxC), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_EnumStatusDocumento", LibTpvCreator.SqlViewStandardEnum(typeof(eStatusDocumento), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_EnumCreditoFiscal", LibTpvCreator.SqlViewStandardEnum(typeof(eCreditoFiscal), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_EnumTipoDeCompra", LibTpvCreator.SqlViewStandardEnum(typeof(eTipoDeCompra), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_EnumTipoDeTransaccionDeLibrosFiscales", LibTpvCreator.SqlViewStandardEnum(typeof(eTipoDeTransaccionDeLibrosFiscales), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_EnumDondeSeEfectuaLaRetencionIVA", LibTpvCreator.SqlViewStandardEnum(typeof(eDondeSeEfectuaLaRetencionIVA), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_EnumTipoDeContribuyenteDelIva", LibTpvCreator.SqlViewStandardEnum(typeof(eTipoDeContribuyenteDelIva), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_EnumGeneradoPor", LibTpvCreator.SqlViewStandardEnum(typeof(eGeneradoPor), InsSql), true, true);
            //vResult = insVistas.Create(DbSchema + ".Gv_EnumStatusDetraccion", LibTpvCreator.SqlViewStandardEnum(typeof(eStatusDetraccion), InsSql), true, true);
            vResult = insVistas.Create(DbSchema + ".Gv_CxP_B1", SqlViewB1(), true);
            insVistas.Dispose();
            return vResult;
        }

        bool CrearProcedimientos() {
            bool vResult = false;
            LibStoredProc insSps = new LibStoredProc();
            vResult = insSps.CreateStoredProcedure(DbSchema + ".Gp_CxPINS", SqlSpInsParameters(), SqlSpIns(), true);
            vResult = insSps.CreateStoredProcedure(DbSchema + ".Gp_CxPUPD", SqlSpUpdParameters(), SqlSpUpd(), true) && vResult;
            vResult = insSps.CreateStoredProcedure(DbSchema + ".Gp_CxPDEL", SqlSpDelParameters(), SqlSpDel(), true) && vResult;
            vResult = insSps.CreateStoredProcedure(DbSchema + ".Gp_CxPGET", SqlSpGetParameters(), SqlSpGet(), true) && vResult;
            vResult = insSps.CreateStoredProcedure(DbSchema + ".Gp_CxPSCH", SqlSpSearchParameters(), SqlSpSearch(), true) && vResult;
            vResult = insSps.CreateStoredProcedure(DbSchema + ".Gp_CxPGetFk", SqlSpGetFKParameters(), SqlSpGetFK(), true) && vResult;
            insSps.Dispose();
            return vResult;
        }
        public bool InstalarTabla() {
            bool vResult = false;
            if (CrearTabla()) {
                CrearVistas();
                CrearProcedimientos();
               

                clsRenglonImpuestoMunicipalRetED insDetailRenImpMunRet = new clsRenglonImpuestoMunicipalRetED();
                vResult =  insDetailRenImpMunRet.InstalarTabla();
                //clsComprobanteDeRetencionDeActividadesEconomicasED insDetailComDeRetDeActEco = new clsComprobanteDeRetencionDeActividadesEconomicasED();
                //vResult = vResult && insDetailComDeRetDeActEco.InstalarTabla();
                //clsResumenRetencionDeActividadesEconomicasED insDetailResRetDeActEco = new clsResumenRetencionDeActividadesEconomicasED();
                //vResult = vResult && insDetailResRetDeActEco.InstalarTabla();
            }
            return vResult;
        }

        public bool InstalarVistasYSps() {
            bool vResult = false;
            if (insDbo.Exists(DbSchema + ".CxP", eDboType.Tabla)) {
                CrearVistas();
                CrearProcedimientos();
                vResult = new clsRenglonImpuestoMunicipalRetED().InstalarVistasYSps();
            //    vResult = vResult && new clsComprobanteDeRetencionDeActividadesEconomicasED().InstalarVistasYSps();
            //    vResult = vResult && new clsResumenRetencionDeActividadesEconomicasED().InstalarVistasYSps();
            }
            return vResult;
        }

        public bool BorrarVistasYSps() {
            bool vResult = false;
            LibStoredProc insSp = new LibStoredProc();
            LibViews insVista = new LibViews();
            vResult = new clsRenglonImpuestoMunicipalRetED().BorrarVistasYSps() ;
            vResult = insSp.Drop(DbSchema + ".Gp_CxPINS") && vResult;
            vResult = insSp.Drop(DbSchema + ".Gp_CxPUPD") && vResult;
            vResult = insSp.Drop(DbSchema + ".Gp_CxPDEL") && vResult;
            vResult = insSp.Drop(DbSchema + ".Gp_CxPGET") && vResult;
            vResult = insSp.Drop(DbSchema + ".Gp_CxPGetFk") && vResult;
            vResult = insSp.Drop(DbSchema + ".Gp_CxPSCH") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_CxP_B1") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumTipoDeCxC") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumStatusDocumento") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumCreditoFiscal") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumTipoDeCompra") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumTipoDeTransaccionDeLibrosFiscales") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumDondeSeEfectuaLaRetencionIVA") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumTipoDeContribuyenteDelIva") && vResult;
            vResult = insVista.Drop(DbSchema + ".Gv_EnumGeneradoPor") && vResult;
            //vResult = insVista.Drop(DbSchema + ".Gv_EnumStatusDetraccion") && vResult;
            insSp.Dispose();
            insVista.Dispose();
            return vResult;
        }
        #endregion //Metodos Generados

    } //End of class clsCxPED

} //End of namespace Galac.Dbo.Dal.CajaChica

