//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galac.Saw.Wrp.Crm.CRMServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRMServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarFactura", ReplyAction="http://tempuri.org/IService1/ActualizarFacturaResponse")]
        string ActualizarFactura(string GUID, string Factura, string Control, string CodigoUsu, System.DateTime FechaEmision, string uname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AnularFactura", ReplyAction="http://tempuri.org/IService1/AnularFacturaResponse")]
        string AnularFactura(string Factura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarDeuda", ReplyAction="http://tempuri.org/IService1/ActualizarDeudaResponse")]
        string ActualizarDeuda(string Factura, decimal MontoAbonado, decimal DeudaVencida, decimal DeudaNoVencida, decimal DeudaTotal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Galac.Saw.Wrp.Crm.CRMServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Galac.Saw.Wrp.Crm.CRMServiceReference.IService1>, Galac.Saw.Wrp.Crm.CRMServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ActualizarFactura(string GUID, string Factura, string Control, string CodigoUsu, System.DateTime FechaEmision, string uname) {
            return base.Channel.ActualizarFactura(GUID, Factura, Control, CodigoUsu, FechaEmision, uname);
        }
        
        public string AnularFactura(string Factura) {
            return base.Channel.AnularFactura(Factura);
        }
        
        public string ActualizarDeuda(string Factura, decimal MontoAbonado, decimal DeudaVencida, decimal DeudaNoVencida, decimal DeudaTotal) {
            return base.Channel.ActualizarDeuda(Factura, MontoAbonado, DeudaVencida, DeudaNoVencida, DeudaTotal);
        }
    }
}
