using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Galac.Adm.Brl.DispositivosExternos{
    public static class clsASCIIUtil{
        public static int NUL = 0;
        public static int SOH = 1;
        public static int STX = 2;
        public static int ETX = 3;
        public static int EOT = 4;
        public static int ENQ = 5;
        public static int ACK = 6;
        public static int BEL = 7;
        public static int BS = 8;
        public static int TAB = 9;
        public static int LF = 10;
        public static int VT = 11;
        public static int FF = 12;
        public static int CR = 13;
        public static int SO = 14;
        public static int SI = 15;
        public static int DLE = 16;
        public static int DC1 = 17;
        public static int DC2 = 18;
        public static int DC3 = 19;
        public static int DC4 = 20;
        public static int NAK = 21;
        public static int SYN = 22;
        public static int ETB = 23;
        public static int CAN = 24;
        public static int EM = 25;
        public static int SUB = 26;
        public static int ESC = 27;
        public static int FS = 28;
        public static int GS = 29;
        public static int RS = 30;
        public static int US = 31;
        public static int SPACE = 32;
        public static int EXCLAMACION = 33;
        public static int DOBLE_COMILLA = 34;
        public static int CHARP = 35;
        public static int DOLLAR = 36;
        public static int PORCENTAJE = 37;
        public static int AMPERSAND = 38;
        public static int COMILLA_SIMPE = 39;
        public static int PARENTESIS_IZQUIERDO = 40;
        public static int PARENTESIS_DERECHO = 41;
        public static int ASTERISCO = 42;
        public static int SUMA = 43;
        public static int COMA = 44;
        public static int GUION = 45;
        public static int PUNTO = 46;
        public static int SLASH = 47;
        public static int NUMERO_0= 48;
        public static int NUMERO_1=49;
        public static int NUMERO_2=50;
        public static int NUMERO_3 = 51;
        public static int NUMERO_4 = 52;
        public static int NUMERO_5 = 53;
        public static int NUMERO_6 = 54;
        public static int NUMERO_7 = 55;
        public static int NUMERO_8 = 56;
        public static int NUMERO_9 = 57;
        public static int DOS_PUNTOS = 58;
        public static int PUNTO_COMA = 59;
        public static int MENOR_QUE = 60;
        public static int IGUAL = 61;
        public static int MAYOR_QUE = 62;
        public static int INTERROGANTE_CIERRE = 63;
        public static int ARROBA = 64;
        public static int LETRA_A_MAYUSCULA = 65;
        public static int LETRA_B_MAYUSCULA = 66;
        public static int LETRA_C_MAYUSCULA = 67;
        public static int LETRA_D_MAYUSCULA = 68;
        public static int LETRA_E_MAYUSCULA = 69;
        public static int LETRA_F_MAYUSCULA = 70;
        public static int LETRA_G_MAYUSCULA = 71;
        public static int LETRA_H_MAYUSCULA = 72;
        public static int LETRA_I_MAYUSCULA = 73;
        public static int LETRA_J_MAYUSCULA = 74;
        public static int LETRA_K_MAYUSCULA = 75;
        public static int LETRA_L_MAYUSCULA = 76;
        public static int LETRA_M_MAYUSCULA = 77;
        public static int LETRA_N_MAYUSCULA = 78;
        public static int LETRA_O_MAYUSCULA = 79;
        public static int LETRA_P_MAYUSCULA = 80;
        public static int LETRA_Q_MAYUSCULA = 81;
        public static int LETRA_R_MAYUSCULA = 82;
        public static int LETRA_S_MAYUSCULA = 83;
        public static int LETRA_T_MAYUSCULA = 84;
        public static int LETRA_U_MAYUSCULA = 85;
        public static int LETRA_V_MAYUSCULA = 86;
        public static int LETRA_W_MAYUSCULA = 87;
        public static int LETRA_X_MAYUSCULA = 88;
        public static int LETRA_Y_MAYUSCULA = 89;
        public static int LETRA_Z_MAYUSCULA = 90;
        public static int CORCHETE_APERTURA = 91;
        public static int BACKSLASH = 92;
        public static int CORCHETE_CIERRE = 93;
        public static int ACENTO_CIRCUNFLEJO = 94;
        public static int GUION_BAJO = 95;
        public static int ACENTO_IZQUIERDO = 96;
        public static int LETRA_A_MINUSCULA = 97;
        public static int LETRA_B_MINUSCULA = 98;
        public static int LETRA_C_MINUSCULA = 99;
        public static int LETRA_D_MINUSCULA = 100;
        public static int LETRA_E_MINUSCULA = 101;
        public static int LETRA_F_MINUSCULA = 102;
        public static int LETRA_G_MINUSCULA = 103;
        public static int LETRA_H_MINUSCULA = 104;
        public static int LETRA_I_MINUSCULA = 105;
        public static int LETRA_J_MINUSCULA = 106;
        public static int LETRA_K_MINUSCULA = 107;
        public static int LETRA_L_MINUSCULA = 108;
        public static int LETRA_M_MINUSCULA = 109;
        public static int LETRA_N_MINUSCULA = 110;
        public static int LETRA_O_MINUSCULA = 111;
        public static int LETRA_P_MINUSCULA = 112;
        public static int LETRA_Q_MINUSCULA = 113;
        public static int LETRA_R_MINUSCULA = 114;
        public static int LETRA_S_MINUSCULA = 115;
        public static int LETRA_T_MINUSCULA = 116;
        public static int LETRA_U_MINUSCULA = 117;
        public static int LETRA_V_MINUSCULA = 118;
        public static int LETRA_W_MINUSCULA = 119;
        public static int LETRA_X_MINUSCULA = 120;
        public static int LETRA_y_MINUSCULA = 121;
        public static int LETRA_Z_MINUSCULA = 122;
        public static int LLAVE_APERTURA = 123;
        public static int BARRA = 124;
        public static int LLAVE_CIERRE = 125;
        public static int TILDE= 126;
        public static int ASCII_127= 127;
        public static char obtenerCharDesdeASCII(int ascii) {
            return (char)ascii;
        }
        public static int obtenerASCIIDesdeChar(char c) {
            return (int)c;
        }
        public static char[] obtenerArregloCharDesdeString(string cadena){
            char[] arreglo = new char[cadena.Length];
            for (int i = 0; i < cadena.Length; i++){
                arreglo[i] = cadena.ElementAt(i);
            }
            return arreglo;
        }
    }
}
